//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Com.Mftvanak.Edusys.Ui.Desktop.PhoneBook.PhoneBookServiceWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PhoneBookSoap11", Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class PhoneBookService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetFollowUpsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPhoneEntriesByPredicateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePhoneEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletePhoneEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddPhoneEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFollowUpByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPhoneEntryByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFollowUpOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateFollowUpOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddFollowUpOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PhoneBookService() {
            this.Url = global::Com.Mftvanak.Edusys.Ui.Desktop.PhoneBook.Properties.Settings.Default.Com_Mftvanak_Edusys_Ui_Desktop_PhoneBook_PhoneBookServiceWebReference_PhoneBookService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetFollowUpsCompletedEventHandler GetFollowUpsCompleted;
        
        /// <remarks/>
        public event GetPhoneEntriesByPredicateCompletedEventHandler GetPhoneEntriesByPredicateCompleted;
        
        /// <remarks/>
        public event UpdatePhoneEntryCompletedEventHandler UpdatePhoneEntryCompleted;
        
        /// <remarks/>
        public event DeletePhoneEntryCompletedEventHandler DeletePhoneEntryCompleted;
        
        /// <remarks/>
        public event AddPhoneEntryCompletedEventHandler AddPhoneEntryCompleted;
        
        /// <remarks/>
        public event GetFollowUpByIdCompletedEventHandler GetFollowUpByIdCompleted;
        
        /// <remarks/>
        public event GetPhoneEntryByIdCompletedEventHandler GetPhoneEntryByIdCompleted;
        
        /// <remarks/>
        public event DeleteFollowUpCompletedEventHandler DeleteFollowUpCompleted;
        
        /// <remarks/>
        public event UpdateFollowUpCompletedEventHandler UpdateFollowUpCompleted;
        
        /// <remarks/>
        public event AddFollowUpCompletedEventHandler AddFollowUpCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetFollowUpsResponse", Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
        public GetFollowUpsResponse GetFollowUps([System.Xml.Serialization.XmlElementAttribute(Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")] GetFollowUpsRequest GetFollowUpsRequest) {
            object[] results = this.Invoke("GetFollowUps", new object[] {
                        GetFollowUpsRequest});
            return ((GetFollowUpsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetFollowUpsAsync(GetFollowUpsRequest GetFollowUpsRequest) {
            this.GetFollowUpsAsync(GetFollowUpsRequest, null);
        }
        
        /// <remarks/>
        public void GetFollowUpsAsync(GetFollowUpsRequest GetFollowUpsRequest, object userState) {
            if ((this.GetFollowUpsOperationCompleted == null)) {
                this.GetFollowUpsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFollowUpsOperationCompleted);
            }
            this.InvokeAsync("GetFollowUps", new object[] {
                        GetFollowUpsRequest}, this.GetFollowUpsOperationCompleted, userState);
        }
        
        private void OnGetFollowUpsOperationCompleted(object arg) {
            if ((this.GetFollowUpsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFollowUpsCompleted(this, new GetFollowUpsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetPhoneEntriesByPredicateResponse", Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
        public GetPhoneEntriesByPredicateResponse GetPhoneEntriesByPredicate([System.Xml.Serialization.XmlElementAttribute(Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")] GetPhoneEntriesByPredicateRequest GetPhoneEntriesByPredicateRequest) {
            object[] results = this.Invoke("GetPhoneEntriesByPredicate", new object[] {
                        GetPhoneEntriesByPredicateRequest});
            return ((GetPhoneEntriesByPredicateResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetPhoneEntriesByPredicateAsync(GetPhoneEntriesByPredicateRequest GetPhoneEntriesByPredicateRequest) {
            this.GetPhoneEntriesByPredicateAsync(GetPhoneEntriesByPredicateRequest, null);
        }
        
        /// <remarks/>
        public void GetPhoneEntriesByPredicateAsync(GetPhoneEntriesByPredicateRequest GetPhoneEntriesByPredicateRequest, object userState) {
            if ((this.GetPhoneEntriesByPredicateOperationCompleted == null)) {
                this.GetPhoneEntriesByPredicateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPhoneEntriesByPredicateOperationCompleted);
            }
            this.InvokeAsync("GetPhoneEntriesByPredicate", new object[] {
                        GetPhoneEntriesByPredicateRequest}, this.GetPhoneEntriesByPredicateOperationCompleted, userState);
        }
        
        private void OnGetPhoneEntriesByPredicateOperationCompleted(object arg) {
            if ((this.GetPhoneEntriesByPredicateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPhoneEntriesByPredicateCompleted(this, new GetPhoneEntriesByPredicateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdatePhoneEntryResponse", Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
        public UpdatePhoneEntryResponse UpdatePhoneEntry([System.Xml.Serialization.XmlElementAttribute(Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")] UpdatePhoneEntryRequest UpdatePhoneEntryRequest) {
            object[] results = this.Invoke("UpdatePhoneEntry", new object[] {
                        UpdatePhoneEntryRequest});
            return ((UpdatePhoneEntryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePhoneEntryAsync(UpdatePhoneEntryRequest UpdatePhoneEntryRequest) {
            this.UpdatePhoneEntryAsync(UpdatePhoneEntryRequest, null);
        }
        
        /// <remarks/>
        public void UpdatePhoneEntryAsync(UpdatePhoneEntryRequest UpdatePhoneEntryRequest, object userState) {
            if ((this.UpdatePhoneEntryOperationCompleted == null)) {
                this.UpdatePhoneEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePhoneEntryOperationCompleted);
            }
            this.InvokeAsync("UpdatePhoneEntry", new object[] {
                        UpdatePhoneEntryRequest}, this.UpdatePhoneEntryOperationCompleted, userState);
        }
        
        private void OnUpdatePhoneEntryOperationCompleted(object arg) {
            if ((this.UpdatePhoneEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePhoneEntryCompleted(this, new UpdatePhoneEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeletePhoneEntryResponse", Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
        public DeletePhoneEntryResponse DeletePhoneEntry([System.Xml.Serialization.XmlElementAttribute(Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")] DeletePhoneEntryRequest DeletePhoneEntryRequest) {
            object[] results = this.Invoke("DeletePhoneEntry", new object[] {
                        DeletePhoneEntryRequest});
            return ((DeletePhoneEntryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeletePhoneEntryAsync(DeletePhoneEntryRequest DeletePhoneEntryRequest) {
            this.DeletePhoneEntryAsync(DeletePhoneEntryRequest, null);
        }
        
        /// <remarks/>
        public void DeletePhoneEntryAsync(DeletePhoneEntryRequest DeletePhoneEntryRequest, object userState) {
            if ((this.DeletePhoneEntryOperationCompleted == null)) {
                this.DeletePhoneEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePhoneEntryOperationCompleted);
            }
            this.InvokeAsync("DeletePhoneEntry", new object[] {
                        DeletePhoneEntryRequest}, this.DeletePhoneEntryOperationCompleted, userState);
        }
        
        private void OnDeletePhoneEntryOperationCompleted(object arg) {
            if ((this.DeletePhoneEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletePhoneEntryCompleted(this, new DeletePhoneEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AddPhoneEntryResponse", Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
        public AddPhoneEntryResponse AddPhoneEntry([System.Xml.Serialization.XmlElementAttribute(Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")] AddPhoneEntryRequest AddPhoneEntryRequest) {
            object[] results = this.Invoke("AddPhoneEntry", new object[] {
                        AddPhoneEntryRequest});
            return ((AddPhoneEntryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AddPhoneEntryAsync(AddPhoneEntryRequest AddPhoneEntryRequest) {
            this.AddPhoneEntryAsync(AddPhoneEntryRequest, null);
        }
        
        /// <remarks/>
        public void AddPhoneEntryAsync(AddPhoneEntryRequest AddPhoneEntryRequest, object userState) {
            if ((this.AddPhoneEntryOperationCompleted == null)) {
                this.AddPhoneEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddPhoneEntryOperationCompleted);
            }
            this.InvokeAsync("AddPhoneEntry", new object[] {
                        AddPhoneEntryRequest}, this.AddPhoneEntryOperationCompleted, userState);
        }
        
        private void OnAddPhoneEntryOperationCompleted(object arg) {
            if ((this.AddPhoneEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddPhoneEntryCompleted(this, new AddPhoneEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetFollowUpByIdResponse", Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
        public GetFollowUpByIdResponse GetFollowUpById([System.Xml.Serialization.XmlElementAttribute(Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")] GetFollowUpByIdRequest GetFollowUpByIdRequest) {
            object[] results = this.Invoke("GetFollowUpById", new object[] {
                        GetFollowUpByIdRequest});
            return ((GetFollowUpByIdResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetFollowUpByIdAsync(GetFollowUpByIdRequest GetFollowUpByIdRequest) {
            this.GetFollowUpByIdAsync(GetFollowUpByIdRequest, null);
        }
        
        /// <remarks/>
        public void GetFollowUpByIdAsync(GetFollowUpByIdRequest GetFollowUpByIdRequest, object userState) {
            if ((this.GetFollowUpByIdOperationCompleted == null)) {
                this.GetFollowUpByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFollowUpByIdOperationCompleted);
            }
            this.InvokeAsync("GetFollowUpById", new object[] {
                        GetFollowUpByIdRequest}, this.GetFollowUpByIdOperationCompleted, userState);
        }
        
        private void OnGetFollowUpByIdOperationCompleted(object arg) {
            if ((this.GetFollowUpByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFollowUpByIdCompleted(this, new GetFollowUpByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetPhoneEntryByIdResponse", Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
        public GetPhoneEntryByIdResponse GetPhoneEntryById([System.Xml.Serialization.XmlElementAttribute(Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")] GetPhoneEntryByIdRequest GetPhoneEntryByIdRequest) {
            object[] results = this.Invoke("GetPhoneEntryById", new object[] {
                        GetPhoneEntryByIdRequest});
            return ((GetPhoneEntryByIdResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetPhoneEntryByIdAsync(GetPhoneEntryByIdRequest GetPhoneEntryByIdRequest) {
            this.GetPhoneEntryByIdAsync(GetPhoneEntryByIdRequest, null);
        }
        
        /// <remarks/>
        public void GetPhoneEntryByIdAsync(GetPhoneEntryByIdRequest GetPhoneEntryByIdRequest, object userState) {
            if ((this.GetPhoneEntryByIdOperationCompleted == null)) {
                this.GetPhoneEntryByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPhoneEntryByIdOperationCompleted);
            }
            this.InvokeAsync("GetPhoneEntryById", new object[] {
                        GetPhoneEntryByIdRequest}, this.GetPhoneEntryByIdOperationCompleted, userState);
        }
        
        private void OnGetPhoneEntryByIdOperationCompleted(object arg) {
            if ((this.GetPhoneEntryByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPhoneEntryByIdCompleted(this, new GetPhoneEntryByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteFollowUpResponse", Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
        public DeleteFollowUpResponse DeleteFollowUp([System.Xml.Serialization.XmlElementAttribute(Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")] DeleteFollowUpRequest DeleteFollowUpRequest) {
            object[] results = this.Invoke("DeleteFollowUp", new object[] {
                        DeleteFollowUpRequest});
            return ((DeleteFollowUpResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFollowUpAsync(DeleteFollowUpRequest DeleteFollowUpRequest) {
            this.DeleteFollowUpAsync(DeleteFollowUpRequest, null);
        }
        
        /// <remarks/>
        public void DeleteFollowUpAsync(DeleteFollowUpRequest DeleteFollowUpRequest, object userState) {
            if ((this.DeleteFollowUpOperationCompleted == null)) {
                this.DeleteFollowUpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFollowUpOperationCompleted);
            }
            this.InvokeAsync("DeleteFollowUp", new object[] {
                        DeleteFollowUpRequest}, this.DeleteFollowUpOperationCompleted, userState);
        }
        
        private void OnDeleteFollowUpOperationCompleted(object arg) {
            if ((this.DeleteFollowUpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFollowUpCompleted(this, new DeleteFollowUpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateFollowUpResponse", Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
        public UpdateFollowUpResponse UpdateFollowUp([System.Xml.Serialization.XmlElementAttribute(Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")] UpdateFollowUpRequest UpdateFollowUpRequest) {
            object[] results = this.Invoke("UpdateFollowUp", new object[] {
                        UpdateFollowUpRequest});
            return ((UpdateFollowUpResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateFollowUpAsync(UpdateFollowUpRequest UpdateFollowUpRequest) {
            this.UpdateFollowUpAsync(UpdateFollowUpRequest, null);
        }
        
        /// <remarks/>
        public void UpdateFollowUpAsync(UpdateFollowUpRequest UpdateFollowUpRequest, object userState) {
            if ((this.UpdateFollowUpOperationCompleted == null)) {
                this.UpdateFollowUpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateFollowUpOperationCompleted);
            }
            this.InvokeAsync("UpdateFollowUp", new object[] {
                        UpdateFollowUpRequest}, this.UpdateFollowUpOperationCompleted, userState);
        }
        
        private void OnUpdateFollowUpOperationCompleted(object arg) {
            if ((this.UpdateFollowUpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateFollowUpCompleted(this, new UpdateFollowUpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AddFollowUpResponse", Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
        public AddFollowUpResponse AddFollowUp([System.Xml.Serialization.XmlElementAttribute(Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")] AddFollowUpRequest AddFollowUpRequest) {
            object[] results = this.Invoke("AddFollowUp", new object[] {
                        AddFollowUpRequest});
            return ((AddFollowUpResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AddFollowUpAsync(AddFollowUpRequest AddFollowUpRequest) {
            this.AddFollowUpAsync(AddFollowUpRequest, null);
        }
        
        /// <remarks/>
        public void AddFollowUpAsync(AddFollowUpRequest AddFollowUpRequest, object userState) {
            if ((this.AddFollowUpOperationCompleted == null)) {
                this.AddFollowUpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddFollowUpOperationCompleted);
            }
            this.InvokeAsync("AddFollowUp", new object[] {
                        AddFollowUpRequest}, this.AddFollowUpOperationCompleted, userState);
        }
        
        private void OnAddFollowUpOperationCompleted(object arg) {
            if ((this.AddFollowUpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddFollowUpCompleted(this, new AddFollowUpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class GetFollowUpsRequest {
        
        private string tokenField;
        
        private long phoneEntryIdField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public long PhoneEntryId {
            get {
                return this.phoneEntryIdField;
            }
            set {
                this.phoneEntryIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class PhoneEntryType {
        
        private long idField;
        
        private long departmentIdField;
        
        private long ownerIdField;
        
        private string colorField;
        
        private string nameField;
        
        private string numberField;
        
        private string descriptionField;
        
        private string questionField;
        
        private int seenField;
        
        private long submitDateField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public long departmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
        
        /// <remarks/>
        public long OwnerId {
            get {
                return this.ownerIdField;
            }
            set {
                this.ownerIdField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Question {
            get {
                return this.questionField;
            }
            set {
                this.questionField = value;
            }
        }
        
        /// <remarks/>
        public int Seen {
            get {
                return this.seenField;
            }
            set {
                this.seenField = value;
            }
        }
        
        /// <remarks/>
        public long SubmitDate {
            get {
                return this.submitDateField;
            }
            set {
                this.submitDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class PhoneEntrySearchPredicateType {
        
        private long departmentIdField;
        
        private long ownerIdField;
        
        private long submitDateStartField;
        
        private long submitDateEndField;
        
        private string nameField;
        
        private string numberField;
        
        private string questionField;
        
        private string descriptionField;
        
        private string[] followUpTypesField;
        
        private string[] colorsField;
        
        /// <remarks/>
        public long DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
        
        /// <remarks/>
        public long OwnerId {
            get {
                return this.ownerIdField;
            }
            set {
                this.ownerIdField = value;
            }
        }
        
        /// <remarks/>
        public long SubmitDateStart {
            get {
                return this.submitDateStartField;
            }
            set {
                this.submitDateStartField = value;
            }
        }
        
        /// <remarks/>
        public long SubmitDateEnd {
            get {
                return this.submitDateEndField;
            }
            set {
                this.submitDateEndField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string Question {
            get {
                return this.questionField;
            }
            set {
                this.questionField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FollowUpTypes")]
        public string[] FollowUpTypes {
            get {
                return this.followUpTypesField;
            }
            set {
                this.followUpTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Colors")]
        public string[] Colors {
            get {
                return this.colorsField;
            }
            set {
                this.colorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class FollowUpType {
        
        private long idField;
        
        private long phoneEntryIdField;
        
        private int ownerIdField;
        
        private string colorField;
        
        private string descriptionField;
        
        private string desiredCoursesField;
        
        private string desiredTimesField;
        
        private int phoneFollowUpTypeField;
        
        private string questionField;
        
        private long submitDateField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public long PhoneEntryId {
            get {
                return this.phoneEntryIdField;
            }
            set {
                this.phoneEntryIdField = value;
            }
        }
        
        /// <remarks/>
        public int OwnerId {
            get {
                return this.ownerIdField;
            }
            set {
                this.ownerIdField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string DesiredCourses {
            get {
                return this.desiredCoursesField;
            }
            set {
                this.desiredCoursesField = value;
            }
        }
        
        /// <remarks/>
        public string DesiredTimes {
            get {
                return this.desiredTimesField;
            }
            set {
                this.desiredTimesField = value;
            }
        }
        
        /// <remarks/>
        public int PhoneFollowUpType {
            get {
                return this.phoneFollowUpTypeField;
            }
            set {
                this.phoneFollowUpTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Question {
            get {
                return this.questionField;
            }
            set {
                this.questionField = value;
            }
        }
        
        /// <remarks/>
        public long SubmitDate {
            get {
                return this.submitDateField;
            }
            set {
                this.submitDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class GetFollowUpsResponse {
        
        private int resultField;
        
        private FollowUpType[] followUpsField;
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FollowUps")]
        public FollowUpType[] FollowUps {
            get {
                return this.followUpsField;
            }
            set {
                this.followUpsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class GetPhoneEntriesByPredicateRequest {
        
        private string tokenField;
        
        private int justTodayField;
        
        private PhoneEntrySearchPredicateType predicateField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public int JustToday {
            get {
                return this.justTodayField;
            }
            set {
                this.justTodayField = value;
            }
        }
        
        /// <remarks/>
        public PhoneEntrySearchPredicateType Predicate {
            get {
                return this.predicateField;
            }
            set {
                this.predicateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class GetPhoneEntriesByPredicateResponse {
        
        private int resultField;
        
        private PhoneEntryType[] phoneEntriesField;
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PhoneEntries")]
        public PhoneEntryType[] PhoneEntries {
            get {
                return this.phoneEntriesField;
            }
            set {
                this.phoneEntriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class UpdatePhoneEntryRequest {
        
        private string tokenField;
        
        private PhoneEntryType phoneEntryField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public PhoneEntryType PhoneEntry {
            get {
                return this.phoneEntryField;
            }
            set {
                this.phoneEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class UpdatePhoneEntryResponse {
        
        private int resultField;
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class DeletePhoneEntryRequest {
        
        private string tokenField;
        
        private long idField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class DeletePhoneEntryResponse {
        
        private int resultField;
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class AddPhoneEntryRequest {
        
        private string tokenField;
        
        private PhoneEntryType phoneEntryField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public PhoneEntryType PhoneEntry {
            get {
                return this.phoneEntryField;
            }
            set {
                this.phoneEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class AddPhoneEntryResponse {
        
        private int resultField;
        
        private long idField;
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class GetFollowUpByIdRequest {
        
        private string tokenField;
        
        private long idField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class GetFollowUpByIdResponse {
        
        private int resultField;
        
        private FollowUpType followUpField;
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public FollowUpType FollowUp {
            get {
                return this.followUpField;
            }
            set {
                this.followUpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class GetPhoneEntryByIdRequest {
        
        private string tokenField;
        
        private long idField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class GetPhoneEntryByIdResponse {
        
        private int resultField;
        
        private PhoneEntryType phoneEntryField;
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public PhoneEntryType PhoneEntry {
            get {
                return this.phoneEntryField;
            }
            set {
                this.phoneEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class DeleteFollowUpRequest {
        
        private string tokenField;
        
        private long idField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class DeleteFollowUpResponse {
        
        private int resultField;
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class UpdateFollowUpRequest {
        
        private string tokenField;
        
        private FollowUpType followUpField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public FollowUpType FollowUp {
            get {
                return this.followUpField;
            }
            set {
                this.followUpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class UpdateFollowUpResponse {
        
        private int resultField;
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class AddFollowUpRequest {
        
        private string tokenField;
        
        private FollowUpType followUpField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public FollowUpType FollowUp {
            get {
                return this.followUpField;
            }
            set {
                this.followUpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://phonebook.ws.edusys.mftvanak.com/schemas")]
    public partial class AddFollowUpResponse {
        
        private int resultField;
        
        private long idField;
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetFollowUpsCompletedEventHandler(object sender, GetFollowUpsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFollowUpsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFollowUpsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetFollowUpsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetFollowUpsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPhoneEntriesByPredicateCompletedEventHandler(object sender, GetPhoneEntriesByPredicateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPhoneEntriesByPredicateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPhoneEntriesByPredicateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetPhoneEntriesByPredicateResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetPhoneEntriesByPredicateResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdatePhoneEntryCompletedEventHandler(object sender, UpdatePhoneEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePhoneEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePhoneEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdatePhoneEntryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdatePhoneEntryResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeletePhoneEntryCompletedEventHandler(object sender, DeletePhoneEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeletePhoneEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeletePhoneEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeletePhoneEntryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeletePhoneEntryResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddPhoneEntryCompletedEventHandler(object sender, AddPhoneEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddPhoneEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddPhoneEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddPhoneEntryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddPhoneEntryResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetFollowUpByIdCompletedEventHandler(object sender, GetFollowUpByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFollowUpByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFollowUpByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetFollowUpByIdResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetFollowUpByIdResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPhoneEntryByIdCompletedEventHandler(object sender, GetPhoneEntryByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPhoneEntryByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPhoneEntryByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetPhoneEntryByIdResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetPhoneEntryByIdResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteFollowUpCompletedEventHandler(object sender, DeleteFollowUpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFollowUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFollowUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteFollowUpResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteFollowUpResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateFollowUpCompletedEventHandler(object sender, UpdateFollowUpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateFollowUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateFollowUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateFollowUpResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateFollowUpResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddFollowUpCompletedEventHandler(object sender, AddFollowUpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddFollowUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddFollowUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddFollowUpResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddFollowUpResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591