//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.04 at 03:34:58 PM IRDT 
//


package com.mftvanak.edusys.ws.personnel.schemas.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContactType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="NodeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DefaultContact" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DisplayAs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RawInformation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactType", propOrder = {
    "id",
    "nodeId",
    "defaultContact",
    "displayAs",
    "type",
    "rawInformation",
    "description"
})
@XmlSeeAlso({
    EmailType.class,
    AddressType.class,
    WebPageType.class,
    PhoneType.class
})
public class ContactType {

    @XmlElement(name = "Id")
    protected long id;
    @XmlElement(name = "NodeId", required = true)
    protected String nodeId;
    @XmlElement(name = "DefaultContact")
    protected int defaultContact;
    @XmlElement(name = "DisplayAs", required = true)
    protected String displayAs;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "RawInformation", required = true)
    protected String rawInformation;
    @XmlElement(name = "Description", required = true)
    protected String description;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the nodeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeId(String value) {
        this.nodeId = value;
    }

    /**
     * Gets the value of the defaultContact property.
     * 
     */
    public int getDefaultContact() {
        return defaultContact;
    }

    /**
     * Sets the value of the defaultContact property.
     * 
     */
    public void setDefaultContact(int value) {
        this.defaultContact = value;
    }

    /**
     * Gets the value of the displayAs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayAs() {
        return displayAs;
    }

    /**
     * Sets the value of the displayAs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayAs(String value) {
        this.displayAs = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the rawInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRawInformation() {
        return rawInformation;
    }

    /**
     * Sets the value of the rawInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRawInformation(String value) {
        this.rawInformation = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
