//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.30 at 04:10:00 PM IRST 
//


package com.mftvanak.edusys.ws.messaging.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.mftvanak.edusys.ws.messaging.schemas.types.SendRequestType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SendRequest" type="{http://messaging.ws.edusys.mftvanak.com/schemas/types}SendRequestType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sendRequest"
})
@XmlRootElement(name = "GetSendRequestByIdResponse")
public class GetSendRequestByIdResponse {

    @XmlElement(name = "SendRequest", required = true)
    protected SendRequestType sendRequest;

    /**
     * Gets the value of the sendRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SendRequestType }
     *     
     */
    public SendRequestType getSendRequest() {
        return sendRequest;
    }

    /**
     * Sets the value of the sendRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendRequestType }
     *     
     */
    public void setSendRequest(SendRequestType value) {
        this.sendRequest = value;
    }

}
