//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.12 at 01:52:53 AM IRST
//

@javax.xml.bind.annotation.XmlSchema (namespace = "http://education.ws.edusys.mftvanak.com/schemas/reservation", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.labcrypto.edusys.ws.education.schemas.reservation;

