//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.12 at 01:52:53 AM IRST
//

package org.labcrypto.edusys.ws.education.schemas.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for CmsGeneralReservationType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="CmsGeneralReservationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="WillRegister" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="WillRegisterWithCondition" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Cancelled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="NotAnswered" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Followed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="WillInformUs" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="HasRegistered" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Seen" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Called" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="SmsSent" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="CmsDepartmentId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="CmsDepartmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CmsGroupId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="CmsGroupName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CmsClassId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="CmsClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CalculatedDate" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType (XmlAccessType.FIELD)
@XmlType (name = "CmsGeneralReservationType", propOrder = {

})
public class CmsGeneralReservationType {

  @XmlElement (name = "Id")
  protected long id;
  @XmlElement (name = "WillRegister", required = true, type = Boolean.class, nillable = true)
  protected Boolean willRegister;
  @XmlElement (name = "WillRegisterWithCondition", required = true, type = Boolean.class, nillable = true)
  protected Boolean willRegisterWithCondition;
  @XmlElement (name = "Cancelled", required = true, type = Boolean.class, nillable = true)
  protected Boolean cancelled;
  @XmlElement (name = "NotAnswered", required = true, type = Boolean.class, nillable = true)
  protected Boolean notAnswered;
  @XmlElement (name = "Followed", required = true, type = Boolean.class, nillable = true)
  protected Boolean followed;
  @XmlElement (name = "WillInformUs", required = true, type = Boolean.class, nillable = true)
  protected Boolean willInformUs;
  @XmlElement (name = "HasRegistered", required = true, type = Boolean.class, nillable = true)
  protected Boolean hasRegistered;
  @XmlElement (name = "Seen")
  protected boolean seen;
  @XmlElement (name = "Called")
  protected boolean called;
  @XmlElement (name = "SmsSent")
  protected boolean smsSent;
  @XmlElement (name = "CmsDepartmentId")
  protected long cmsDepartmentId;
  @XmlElement (name = "CmsDepartmentName", required = true)
  protected String cmsDepartmentName;
  @XmlElement (name = "CmsGroupId")
  protected long cmsGroupId;
  @XmlElement (name = "CmsGroupName", required = true)
  protected String cmsGroupName;
  @XmlElement (name = "CmsClassId")
  protected long cmsClassId;
  @XmlElement (name = "CmsClassName", required = true)
  protected String cmsClassName;
  @XmlElement (name = "CalculatedDate")
  protected long calculatedDate;
  @XmlElement (name = "Date", required = true)
  protected String date;
  @XmlElement (name = "Name", required = true)
  protected String name;
  @XmlElement (name = "Email", required = true)
  protected String email;
  @XmlElement (name = "Phone", required = true)
  protected String phone;
  @XmlElement (name = "Text", required = true)
  protected String text;
  @XmlElement (name = "Description", required = true)
  protected String description;
  @XmlElement (name = "Source", required = true)
  protected String source;

  /**
   * Gets the value of the id property.
   * 
   */
  public long getId () {
    return id;
  }

  /**
   * Sets the value of the id property.
   * 
   */
  public void setId (long value) {
    this.id = value;
  }

  /**
   * Gets the value of the willRegister property.
   * 
   * @return possible object is {@link Boolean }
   * 
   */
  public Boolean isWillRegister () {
    return willRegister;
  }

  /**
   * Sets the value of the willRegister property.
   * 
   * @param value
   *          allowed object is {@link Boolean }
   * 
   */
  public void setWillRegister (Boolean value) {
    this.willRegister = value;
  }

  /**
   * Gets the value of the willRegisterWithCondition property.
   * 
   * @return possible object is {@link Boolean }
   * 
   */
  public Boolean isWillRegisterWithCondition () {
    return willRegisterWithCondition;
  }

  /**
   * Sets the value of the willRegisterWithCondition property.
   * 
   * @param value
   *          allowed object is {@link Boolean }
   * 
   */
  public void setWillRegisterWithCondition (Boolean value) {
    this.willRegisterWithCondition = value;
  }

  /**
   * Gets the value of the cancelled property.
   * 
   * @return possible object is {@link Boolean }
   * 
   */
  public Boolean isCancelled () {
    return cancelled;
  }

  /**
   * Sets the value of the cancelled property.
   * 
   * @param value
   *          allowed object is {@link Boolean }
   * 
   */
  public void setCancelled (Boolean value) {
    this.cancelled = value;
  }

  /**
   * Gets the value of the notAnswered property.
   * 
   * @return possible object is {@link Boolean }
   * 
   */
  public Boolean isNotAnswered () {
    return notAnswered;
  }

  /**
   * Sets the value of the notAnswered property.
   * 
   * @param value
   *          allowed object is {@link Boolean }
   * 
   */
  public void setNotAnswered (Boolean value) {
    this.notAnswered = value;
  }

  /**
   * Gets the value of the followed property.
   * 
   * @return possible object is {@link Boolean }
   * 
   */
  public Boolean isFollowed () {
    return followed;
  }

  /**
   * Sets the value of the followed property.
   * 
   * @param value
   *          allowed object is {@link Boolean }
   * 
   */
  public void setFollowed (Boolean value) {
    this.followed = value;
  }

  /**
   * Gets the value of the willInformUs property.
   * 
   * @return possible object is {@link Boolean }
   * 
   */
  public Boolean isWillInformUs () {
    return willInformUs;
  }

  /**
   * Sets the value of the willInformUs property.
   * 
   * @param value
   *          allowed object is {@link Boolean }
   * 
   */
  public void setWillInformUs (Boolean value) {
    this.willInformUs = value;
  }

  /**
   * Gets the value of the hasRegistered property.
   * 
   * @return possible object is {@link Boolean }
   * 
   */
  public Boolean isHasRegistered () {
    return hasRegistered;
  }

  /**
   * Sets the value of the hasRegistered property.
   * 
   * @param value
   *          allowed object is {@link Boolean }
   * 
   */
  public void setHasRegistered (Boolean value) {
    this.hasRegistered = value;
  }

  /**
   * Gets the value of the seen property.
   * 
   */
  public boolean isSeen () {
    return seen;
  }

  /**
   * Sets the value of the seen property.
   * 
   */
  public void setSeen (boolean value) {
    this.seen = value;
  }

  /**
   * Gets the value of the called property.
   * 
   */
  public boolean isCalled () {
    return called;
  }

  /**
   * Sets the value of the called property.
   * 
   */
  public void setCalled (boolean value) {
    this.called = value;
  }

  /**
   * Gets the value of the smsSent property.
   * 
   */
  public boolean isSmsSent () {
    return smsSent;
  }

  /**
   * Sets the value of the smsSent property.
   * 
   */
  public void setSmsSent (boolean value) {
    this.smsSent = value;
  }

  /**
   * Gets the value of the cmsDepartmentId property.
   * 
   */
  public long getCmsDepartmentId () {
    return cmsDepartmentId;
  }

  /**
   * Sets the value of the cmsDepartmentId property.
   * 
   */
  public void setCmsDepartmentId (long value) {
    this.cmsDepartmentId = value;
  }

  /**
   * Gets the value of the cmsDepartmentName property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getCmsDepartmentName () {
    return cmsDepartmentName;
  }

  /**
   * Sets the value of the cmsDepartmentName property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setCmsDepartmentName (String value) {
    this.cmsDepartmentName = value;
  }

  /**
   * Gets the value of the cmsGroupId property.
   * 
   */
  public long getCmsGroupId () {
    return cmsGroupId;
  }

  /**
   * Sets the value of the cmsGroupId property.
   * 
   */
  public void setCmsGroupId (long value) {
    this.cmsGroupId = value;
  }

  /**
   * Gets the value of the cmsGroupName property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getCmsGroupName () {
    return cmsGroupName;
  }

  /**
   * Sets the value of the cmsGroupName property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setCmsGroupName (String value) {
    this.cmsGroupName = value;
  }

  /**
   * Gets the value of the cmsClassId property.
   * 
   */
  public long getCmsClassId () {
    return cmsClassId;
  }

  /**
   * Sets the value of the cmsClassId property.
   * 
   */
  public void setCmsClassId (long value) {
    this.cmsClassId = value;
  }

  /**
   * Gets the value of the cmsClassName property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getCmsClassName () {
    return cmsClassName;
  }

  /**
   * Sets the value of the cmsClassName property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setCmsClassName (String value) {
    this.cmsClassName = value;
  }

  /**
   * Gets the value of the calculatedDate property.
   * 
   */
  public long getCalculatedDate () {
    return calculatedDate;
  }

  /**
   * Sets the value of the calculatedDate property.
   * 
   */
  public void setCalculatedDate (long value) {
    this.calculatedDate = value;
  }

  /**
   * Gets the value of the date property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDate () {
    return date;
  }

  /**
   * Sets the value of the date property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setDate (String value) {
    this.date = value;
  }

  /**
   * Gets the value of the name property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getName () {
    return name;
  }

  /**
   * Sets the value of the name property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setName (String value) {
    this.name = value;
  }

  /**
   * Gets the value of the email property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getEmail () {
    return email;
  }

  /**
   * Sets the value of the email property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setEmail (String value) {
    this.email = value;
  }

  /**
   * Gets the value of the phone property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getPhone () {
    return phone;
  }

  /**
   * Sets the value of the phone property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setPhone (String value) {
    this.phone = value;
  }

  /**
   * Gets the value of the text property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getText () {
    return text;
  }

  /**
   * Sets the value of the text property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setText (String value) {
    this.text = value;
  }

  /**
   * Gets the value of the description property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDescription () {
    return description;
  }

  /**
   * Sets the value of the description property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setDescription (String value) {
    this.description = value;
  }

  /**
   * Gets the value of the source property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSource () {
    return source;
  }

  /**
   * Sets the value of the source property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setSource (String value) {
    this.source = value;
  }

}
