//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Com.MftVanak.EduSys.Ui.Desktop.Win.Apps.ServiceClients.DepartmentWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DepartmentServiceSoap11", Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")]
    public partial class DepartmentServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DeleteDepartmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDepartmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddDepartmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DepartmentServiceService() {
            this.Url = global::Com.MftVanak.EduSys.Ui.Desktop.Win.Apps.ServiceClients.Properties.Settings.Default.Com_MftVanak_EduSys_Ui_Desktop_Win_Apps_ServiceClients_DepartmentWebReference_DepartmentServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DeleteDepartmentCompletedEventHandler DeleteDepartmentCompleted;
        
        /// <remarks/>
        public event UpdateDepartmentCompletedEventHandler UpdateDepartmentCompleted;
        
        /// <remarks/>
        public event GetDepartmentByIdCompletedEventHandler GetDepartmentByIdCompleted;
        
        /// <remarks/>
        public event AddDepartmentCompletedEventHandler AddDepartmentCompleted;
        
        /// <remarks/>
        public event GetDepartmentsCompletedEventHandler GetDepartmentsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteDepartmentResponse", Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")]
        public DeleteDepartmentResponse DeleteDepartment([System.Xml.Serialization.XmlElementAttribute(Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")] DeleteDepartmentRequest DeleteDepartmentRequest) {
            object[] results = this.Invoke("DeleteDepartment", new object[] {
                        DeleteDepartmentRequest});
            return ((DeleteDepartmentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteDepartmentAsync(DeleteDepartmentRequest DeleteDepartmentRequest) {
            this.DeleteDepartmentAsync(DeleteDepartmentRequest, null);
        }
        
        /// <remarks/>
        public void DeleteDepartmentAsync(DeleteDepartmentRequest DeleteDepartmentRequest, object userState) {
            if ((this.DeleteDepartmentOperationCompleted == null)) {
                this.DeleteDepartmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteDepartmentOperationCompleted);
            }
            this.InvokeAsync("DeleteDepartment", new object[] {
                        DeleteDepartmentRequest}, this.DeleteDepartmentOperationCompleted, userState);
        }
        
        private void OnDeleteDepartmentOperationCompleted(object arg) {
            if ((this.DeleteDepartmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteDepartmentCompleted(this, new DeleteDepartmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateDepartmentResponse", Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")]
        public UpdateDepartmentResponse UpdateDepartment([System.Xml.Serialization.XmlElementAttribute(Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")] UpdateDepartmentRequest UpdateDepartmentRequest) {
            object[] results = this.Invoke("UpdateDepartment", new object[] {
                        UpdateDepartmentRequest});
            return ((UpdateDepartmentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateDepartmentAsync(UpdateDepartmentRequest UpdateDepartmentRequest) {
            this.UpdateDepartmentAsync(UpdateDepartmentRequest, null);
        }
        
        /// <remarks/>
        public void UpdateDepartmentAsync(UpdateDepartmentRequest UpdateDepartmentRequest, object userState) {
            if ((this.UpdateDepartmentOperationCompleted == null)) {
                this.UpdateDepartmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDepartmentOperationCompleted);
            }
            this.InvokeAsync("UpdateDepartment", new object[] {
                        UpdateDepartmentRequest}, this.UpdateDepartmentOperationCompleted, userState);
        }
        
        private void OnUpdateDepartmentOperationCompleted(object arg) {
            if ((this.UpdateDepartmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDepartmentCompleted(this, new UpdateDepartmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetDepartmentByIdResponse", Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")]
        public GetDepartmentByIdResponse GetDepartmentById([System.Xml.Serialization.XmlElementAttribute(Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")] GetDepartmentByIdRequest GetDepartmentByIdRequest) {
            object[] results = this.Invoke("GetDepartmentById", new object[] {
                        GetDepartmentByIdRequest});
            return ((GetDepartmentByIdResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentByIdAsync(GetDepartmentByIdRequest GetDepartmentByIdRequest) {
            this.GetDepartmentByIdAsync(GetDepartmentByIdRequest, null);
        }
        
        /// <remarks/>
        public void GetDepartmentByIdAsync(GetDepartmentByIdRequest GetDepartmentByIdRequest, object userState) {
            if ((this.GetDepartmentByIdOperationCompleted == null)) {
                this.GetDepartmentByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentByIdOperationCompleted);
            }
            this.InvokeAsync("GetDepartmentById", new object[] {
                        GetDepartmentByIdRequest}, this.GetDepartmentByIdOperationCompleted, userState);
        }
        
        private void OnGetDepartmentByIdOperationCompleted(object arg) {
            if ((this.GetDepartmentByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentByIdCompleted(this, new GetDepartmentByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AddDepartmentResponse", Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")]
        public AddDepartmentResponse AddDepartment([System.Xml.Serialization.XmlElementAttribute(Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")] AddDepartmentRequest AddDepartmentRequest) {
            object[] results = this.Invoke("AddDepartment", new object[] {
                        AddDepartmentRequest});
            return ((AddDepartmentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AddDepartmentAsync(AddDepartmentRequest AddDepartmentRequest) {
            this.AddDepartmentAsync(AddDepartmentRequest, null);
        }
        
        /// <remarks/>
        public void AddDepartmentAsync(AddDepartmentRequest AddDepartmentRequest, object userState) {
            if ((this.AddDepartmentOperationCompleted == null)) {
                this.AddDepartmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddDepartmentOperationCompleted);
            }
            this.InvokeAsync("AddDepartment", new object[] {
                        AddDepartmentRequest}, this.AddDepartmentOperationCompleted, userState);
        }
        
        private void OnAddDepartmentOperationCompleted(object arg) {
            if ((this.AddDepartmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddDepartmentCompleted(this, new AddDepartmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetDepartmentsResponse", Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Departments", IsNullable=false)]
        public DepartmentType[] GetDepartments([System.Xml.Serialization.XmlElementAttribute(Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")] GetDepartmentsRequest GetDepartmentsRequest) {
            object[] results = this.Invoke("GetDepartments", new object[] {
                        GetDepartmentsRequest});
            return ((DepartmentType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentsAsync(GetDepartmentsRequest GetDepartmentsRequest) {
            this.GetDepartmentsAsync(GetDepartmentsRequest, null);
        }
        
        /// <remarks/>
        public void GetDepartmentsAsync(GetDepartmentsRequest GetDepartmentsRequest, object userState) {
            if ((this.GetDepartmentsOperationCompleted == null)) {
                this.GetDepartmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentsOperationCompleted);
            }
            this.InvokeAsync("GetDepartments", new object[] {
                        GetDepartmentsRequest}, this.GetDepartmentsOperationCompleted, userState);
        }
        
        private void OnGetDepartmentsOperationCompleted(object arg) {
            if ((this.GetDepartmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentsCompleted(this, new GetDepartmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")]
    public partial class DeleteDepartmentRequest {
        
        private int clientDateTimeYearField;
        
        private int clientDateTimeMonthField;
        
        private int clientDateTimeDayField;
        
        private int clientDateTimeHourField;
        
        private int clientDateTimeMinuteField;
        
        private int clientDateTimeSecondField;
        
        private int clientDateTimeMilliSecondField;
        
        private string clientMacAddressField;
        
        private string clientIpAddressField;
        
        private string clientComputerNameField;
        
        private string applicationNameField;
        
        private string tokenField;
        
        private long departmentIdField;
        
        /// <remarks/>
        public int ClientDateTimeYear {
            get {
                return this.clientDateTimeYearField;
            }
            set {
                this.clientDateTimeYearField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMonth {
            get {
                return this.clientDateTimeMonthField;
            }
            set {
                this.clientDateTimeMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeDay {
            get {
                return this.clientDateTimeDayField;
            }
            set {
                this.clientDateTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeHour {
            get {
                return this.clientDateTimeHourField;
            }
            set {
                this.clientDateTimeHourField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMinute {
            get {
                return this.clientDateTimeMinuteField;
            }
            set {
                this.clientDateTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeSecond {
            get {
                return this.clientDateTimeSecondField;
            }
            set {
                this.clientDateTimeSecondField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMilliSecond {
            get {
                return this.clientDateTimeMilliSecondField;
            }
            set {
                this.clientDateTimeMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientComputerName {
            get {
                return this.clientComputerNameField;
            }
            set {
                this.clientComputerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public long DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://education.ws.edusys.mftvanak.com/schemas/types")]
    public partial class DepartmentType {
        
        private long idField;
        
        private long instituteIdField;
        
        private string persianNameField;
        
        private string englishNameField;
        
        private string colorField;
        
        private int showOrderField;
        
        private string seoKeywordsField;
        
        private string seoDescriptionField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public long InstituteId {
            get {
                return this.instituteIdField;
            }
            set {
                this.instituteIdField = value;
            }
        }
        
        /// <remarks/>
        public string PersianName {
            get {
                return this.persianNameField;
            }
            set {
                this.persianNameField = value;
            }
        }
        
        /// <remarks/>
        public string EnglishName {
            get {
                return this.englishNameField;
            }
            set {
                this.englishNameField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public int ShowOrder {
            get {
                return this.showOrderField;
            }
            set {
                this.showOrderField = value;
            }
        }
        
        /// <remarks/>
        public string SeoKeywords {
            get {
                return this.seoKeywordsField;
            }
            set {
                this.seoKeywordsField = value;
            }
        }
        
        /// <remarks/>
        public string SeoDescription {
            get {
                return this.seoDescriptionField;
            }
            set {
                this.seoDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")]
    public partial class DeleteDepartmentResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")]
    public partial class UpdateDepartmentRequest {
        
        private int clientDateTimeYearField;
        
        private int clientDateTimeMonthField;
        
        private int clientDateTimeDayField;
        
        private int clientDateTimeHourField;
        
        private int clientDateTimeMinuteField;
        
        private int clientDateTimeSecondField;
        
        private int clientDateTimeMilliSecondField;
        
        private string clientMacAddressField;
        
        private string clientIpAddressField;
        
        private string clientComputerNameField;
        
        private string applicationNameField;
        
        private string tokenField;
        
        private DepartmentType departmentField;
        
        /// <remarks/>
        public int ClientDateTimeYear {
            get {
                return this.clientDateTimeYearField;
            }
            set {
                this.clientDateTimeYearField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMonth {
            get {
                return this.clientDateTimeMonthField;
            }
            set {
                this.clientDateTimeMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeDay {
            get {
                return this.clientDateTimeDayField;
            }
            set {
                this.clientDateTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeHour {
            get {
                return this.clientDateTimeHourField;
            }
            set {
                this.clientDateTimeHourField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMinute {
            get {
                return this.clientDateTimeMinuteField;
            }
            set {
                this.clientDateTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeSecond {
            get {
                return this.clientDateTimeSecondField;
            }
            set {
                this.clientDateTimeSecondField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMilliSecond {
            get {
                return this.clientDateTimeMilliSecondField;
            }
            set {
                this.clientDateTimeMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientComputerName {
            get {
                return this.clientComputerNameField;
            }
            set {
                this.clientComputerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public DepartmentType Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")]
    public partial class UpdateDepartmentResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")]
    public partial class GetDepartmentByIdRequest {
        
        private int clientDateTimeYearField;
        
        private int clientDateTimeMonthField;
        
        private int clientDateTimeDayField;
        
        private int clientDateTimeHourField;
        
        private int clientDateTimeMinuteField;
        
        private int clientDateTimeSecondField;
        
        private int clientDateTimeMilliSecondField;
        
        private string clientMacAddressField;
        
        private string clientIpAddressField;
        
        private string clientComputerNameField;
        
        private string applicationNameField;
        
        private string tokenField;
        
        private long departmentIdField;
        
        /// <remarks/>
        public int ClientDateTimeYear {
            get {
                return this.clientDateTimeYearField;
            }
            set {
                this.clientDateTimeYearField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMonth {
            get {
                return this.clientDateTimeMonthField;
            }
            set {
                this.clientDateTimeMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeDay {
            get {
                return this.clientDateTimeDayField;
            }
            set {
                this.clientDateTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeHour {
            get {
                return this.clientDateTimeHourField;
            }
            set {
                this.clientDateTimeHourField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMinute {
            get {
                return this.clientDateTimeMinuteField;
            }
            set {
                this.clientDateTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeSecond {
            get {
                return this.clientDateTimeSecondField;
            }
            set {
                this.clientDateTimeSecondField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMilliSecond {
            get {
                return this.clientDateTimeMilliSecondField;
            }
            set {
                this.clientDateTimeMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientComputerName {
            get {
                return this.clientComputerNameField;
            }
            set {
                this.clientComputerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public long DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")]
    public partial class GetDepartmentByIdResponse {
        
        private DepartmentType departmentField;
        
        /// <remarks/>
        public DepartmentType Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")]
    public partial class AddDepartmentRequest {
        
        private int clientDateTimeYearField;
        
        private int clientDateTimeMonthField;
        
        private int clientDateTimeDayField;
        
        private int clientDateTimeHourField;
        
        private int clientDateTimeMinuteField;
        
        private int clientDateTimeSecondField;
        
        private int clientDateTimeMilliSecondField;
        
        private string clientMacAddressField;
        
        private string clientIpAddressField;
        
        private string clientComputerNameField;
        
        private string applicationNameField;
        
        private string tokenField;
        
        private DepartmentType departmentField;
        
        /// <remarks/>
        public int ClientDateTimeYear {
            get {
                return this.clientDateTimeYearField;
            }
            set {
                this.clientDateTimeYearField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMonth {
            get {
                return this.clientDateTimeMonthField;
            }
            set {
                this.clientDateTimeMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeDay {
            get {
                return this.clientDateTimeDayField;
            }
            set {
                this.clientDateTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeHour {
            get {
                return this.clientDateTimeHourField;
            }
            set {
                this.clientDateTimeHourField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMinute {
            get {
                return this.clientDateTimeMinuteField;
            }
            set {
                this.clientDateTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeSecond {
            get {
                return this.clientDateTimeSecondField;
            }
            set {
                this.clientDateTimeSecondField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMilliSecond {
            get {
                return this.clientDateTimeMilliSecondField;
            }
            set {
                this.clientDateTimeMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientComputerName {
            get {
                return this.clientComputerNameField;
            }
            set {
                this.clientComputerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public DepartmentType Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")]
    public partial class AddDepartmentResponse {
        
        private long departmentIdField;
        
        /// <remarks/>
        public long DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://education.ws.edusys.mftvanak.com/schemas/department")]
    public partial class GetDepartmentsRequest {
        
        private int clientDateTimeYearField;
        
        private int clientDateTimeMonthField;
        
        private int clientDateTimeDayField;
        
        private int clientDateTimeHourField;
        
        private int clientDateTimeMinuteField;
        
        private int clientDateTimeSecondField;
        
        private int clientDateTimeMilliSecondField;
        
        private string clientMacAddressField;
        
        private string clientIpAddressField;
        
        private string clientComputerNameField;
        
        private string applicationNameField;
        
        private string tokenField;
        
        private long instituteIdField;
        
        /// <remarks/>
        public int ClientDateTimeYear {
            get {
                return this.clientDateTimeYearField;
            }
            set {
                this.clientDateTimeYearField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMonth {
            get {
                return this.clientDateTimeMonthField;
            }
            set {
                this.clientDateTimeMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeDay {
            get {
                return this.clientDateTimeDayField;
            }
            set {
                this.clientDateTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeHour {
            get {
                return this.clientDateTimeHourField;
            }
            set {
                this.clientDateTimeHourField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMinute {
            get {
                return this.clientDateTimeMinuteField;
            }
            set {
                this.clientDateTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeSecond {
            get {
                return this.clientDateTimeSecondField;
            }
            set {
                this.clientDateTimeSecondField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMilliSecond {
            get {
                return this.clientDateTimeMilliSecondField;
            }
            set {
                this.clientDateTimeMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientComputerName {
            get {
                return this.clientComputerNameField;
            }
            set {
                this.clientComputerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public long InstituteId {
            get {
                return this.instituteIdField;
            }
            set {
                this.instituteIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteDepartmentCompletedEventHandler(object sender, DeleteDepartmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteDepartmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteDepartmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteDepartmentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteDepartmentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateDepartmentCompletedEventHandler(object sender, UpdateDepartmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateDepartmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateDepartmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateDepartmentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateDepartmentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDepartmentByIdCompletedEventHandler(object sender, GetDepartmentByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetDepartmentByIdResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetDepartmentByIdResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddDepartmentCompletedEventHandler(object sender, AddDepartmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddDepartmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddDepartmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddDepartmentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddDepartmentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDepartmentsCompletedEventHandler(object sender, GetDepartmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepartmentType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepartmentType[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591