//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.19 at 01:22:38 AM IRDT 
//


package com.mftvanak.edusys.ws.phonebook.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PhoneEntryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhoneEntryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="InstituteId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="DepartmentId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="OwnerId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="DepartmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OwnerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Color" type="{http://phonebook.ws.edusys.mftvanak.com/schemas}ColorType"/>
 *         &lt;element name="MethodDeConnaissance" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Seen" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ShouldBeFollowed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Registered" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Private" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="SubmitDate" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Response" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhoneEntryType", propOrder = {
    "id",
    "instituteId",
    "departmentId",
    "ownerId",
    "departmentName",
    "ownerName",
    "color",
    "methodDeConnaissance",
    "seen",
    "shouldBeFollowed",
    "registered",
    "_private",
    "submitDate",
    "name",
    "number",
    "description",
    "response"
})
public class PhoneEntryType {

    @XmlElement(name = "Id")
    protected long id;
    @XmlElement(name = "InstituteId")
    protected long instituteId;
    @XmlElement(name = "DepartmentId")
    protected long departmentId;
    @XmlElement(name = "OwnerId")
    protected long ownerId;
    @XmlElement(name = "DepartmentName", required = true)
    protected String departmentName;
    @XmlElement(name = "OwnerName", required = true)
    protected String ownerName;
    @XmlElement(name = "Color", required = true, nillable = true)
    protected ColorType color;
    @XmlElement(name = "MethodDeConnaissance")
    protected int methodDeConnaissance;
    @XmlElement(name = "Seen", required = true, type = Boolean.class, nillable = true)
    protected Boolean seen;
    @XmlElement(name = "ShouldBeFollowed", required = true, type = Boolean.class, nillable = true)
    protected Boolean shouldBeFollowed;
    @XmlElement(name = "Registered", required = true, type = Boolean.class, nillable = true)
    protected Boolean registered;
    @XmlElement(name = "Private", required = true, type = Boolean.class, nillable = true)
    protected Boolean _private;
    @XmlElement(name = "SubmitDate")
    protected long submitDate;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Number", required = true)
    protected String number;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Response", required = true)
    protected String response;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the instituteId property.
     * 
     */
    public long getInstituteId() {
        return instituteId;
    }

    /**
     * Sets the value of the instituteId property.
     * 
     */
    public void setInstituteId(long value) {
        this.instituteId = value;
    }

    /**
     * Gets the value of the departmentId property.
     * 
     */
    public long getDepartmentId() {
        return departmentId;
    }

    /**
     * Sets the value of the departmentId property.
     * 
     */
    public void setDepartmentId(long value) {
        this.departmentId = value;
    }

    /**
     * Gets the value of the ownerId property.
     * 
     */
    public long getOwnerId() {
        return ownerId;
    }

    /**
     * Sets the value of the ownerId property.
     * 
     */
    public void setOwnerId(long value) {
        this.ownerId = value;
    }

    /**
     * Gets the value of the departmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * Sets the value of the departmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentName(String value) {
        this.departmentName = value;
    }

    /**
     * Gets the value of the ownerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * Sets the value of the ownerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerName(String value) {
        this.ownerName = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link ColorType }
     *     
     */
    public ColorType getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorType }
     *     
     */
    public void setColor(ColorType value) {
        this.color = value;
    }

    /**
     * Gets the value of the methodDeConnaissance property.
     * 
     */
    public int getMethodDeConnaissance() {
        return methodDeConnaissance;
    }

    /**
     * Sets the value of the methodDeConnaissance property.
     * 
     */
    public void setMethodDeConnaissance(int value) {
        this.methodDeConnaissance = value;
    }

    /**
     * Gets the value of the seen property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSeen() {
        return seen;
    }

    /**
     * Sets the value of the seen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSeen(Boolean value) {
        this.seen = value;
    }

    /**
     * Gets the value of the shouldBeFollowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShouldBeFollowed() {
        return shouldBeFollowed;
    }

    /**
     * Sets the value of the shouldBeFollowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShouldBeFollowed(Boolean value) {
        this.shouldBeFollowed = value;
    }

    /**
     * Gets the value of the registered property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRegistered() {
        return registered;
    }

    /**
     * Sets the value of the registered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRegistered(Boolean value) {
        this.registered = value;
    }

    /**
     * Gets the value of the private property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrivate() {
        return _private;
    }

    /**
     * Sets the value of the private property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrivate(Boolean value) {
        this._private = value;
    }

    /**
     * Gets the value of the submitDate property.
     * 
     */
    public long getSubmitDate() {
        return submitDate;
    }

    /**
     * Sets the value of the submitDate property.
     * 
     */
    public void setSubmitDate(long value) {
        this.submitDate = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponse(String value) {
        this.response = value;
    }

}
