//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.19 at 01:12:23 AM IRDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://official.ws.edusys.mftvanak.com/schemas/types", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mftvanak.edusys.ws.official.schemas.types;
