//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.03 at 02:30:04 AM IRDT 
//


package com.mftvanak.edusys.ws.portal.schemas;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mftvanak.edusys.ws.portal.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mftvanak.edusys.ws.portal.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDefaultInstituteIdRequest }
     * 
     */
    public GetDefaultInstituteIdRequest createGetDefaultInstituteIdRequest() {
        return new GetDefaultInstituteIdRequest();
    }

    /**
     * Create an instance of {@link GetDefaultInstituteIdResponse }
     * 
     */
    public GetDefaultInstituteIdResponse createGetDefaultInstituteIdResponse() {
        return new GetDefaultInstituteIdResponse();
    }

    /**
     * Create an instance of {@link GetDepartmentsResponse }
     * 
     */
    public GetDepartmentsResponse createGetDepartmentsResponse() {
        return new GetDepartmentsResponse();
    }

    /**
     * Create an instance of {@link DepartmentType }
     * 
     */
    public DepartmentType createDepartmentType() {
        return new DepartmentType();
    }

    /**
     * Create an instance of {@link GetDepartmentsRequest }
     * 
     */
    public GetDepartmentsRequest createGetDepartmentsRequest() {
        return new GetDepartmentsRequest();
    }

}
