//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.12 at 04:28:58 PM IRST 
//


package com.mftvanak.edusys.ws.messaging.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.mftvanak.edusys.ws.messaging.schemas.types.SendListItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SendListItems" type="{http://messaging.ws.edusys.mftvanak.com/schemas/types}SendListItemType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sendListItems"
})
@XmlRootElement(name = "GetSendListItemsByOwnerIdResponse")
public class GetSendListItemsByOwnerIdResponse {

    @XmlElement(name = "SendListItems", required = true)
    protected List<SendListItemType> sendListItems;

    /**
     * Gets the value of the sendListItems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sendListItems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSendListItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SendListItemType }
     * 
     * 
     */
    public List<SendListItemType> getSendListItems() {
        if (sendListItems == null) {
            sendListItems = new ArrayList<SendListItemType>();
        }
        return this.sendListItems;
    }

}
