//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.12 at 04:28:58 PM IRST 
//


package com.mftvanak.edusys.ws.messaging.schemas.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageTemplateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageTemplateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="OwnerId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="OwnerFullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SubmitDateTimeYear" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SubmitDateTimeMonth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SubmitDateTimeDay" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SubmitDateTimeHour" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SubmitDateTimeMinute" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SubmitDateTimeSecond" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SubmitDateTimeMilliSecond" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageTemplateType", propOrder = {

})
public class MessageTemplateType {

    @XmlElement(name = "Id")
    protected long id;
    @XmlElement(name = "OwnerId")
    protected long ownerId;
    @XmlElement(name = "OwnerFullName", required = true)
    protected String ownerFullName;
    @XmlElement(name = "Type")
    protected int type;
    @XmlElement(name = "SubmitDateTimeYear")
    protected int submitDateTimeYear;
    @XmlElement(name = "SubmitDateTimeMonth")
    protected int submitDateTimeMonth;
    @XmlElement(name = "SubmitDateTimeDay")
    protected int submitDateTimeDay;
    @XmlElement(name = "SubmitDateTimeHour")
    protected int submitDateTimeHour;
    @XmlElement(name = "SubmitDateTimeMinute")
    protected int submitDateTimeMinute;
    @XmlElement(name = "SubmitDateTimeSecond")
    protected int submitDateTimeSecond;
    @XmlElement(name = "SubmitDateTimeMilliSecond")
    protected int submitDateTimeMilliSecond;
    @XmlElement(name = "Text", required = true)
    protected String text;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Description", required = true)
    protected String description;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the ownerId property.
     * 
     */
    public long getOwnerId() {
        return ownerId;
    }

    /**
     * Sets the value of the ownerId property.
     * 
     */
    public void setOwnerId(long value) {
        this.ownerId = value;
    }

    /**
     * Gets the value of the ownerFullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerFullName() {
        return ownerFullName;
    }

    /**
     * Sets the value of the ownerFullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerFullName(String value) {
        this.ownerFullName = value;
    }

    /**
     * Gets the value of the type property.
     * 
     */
    public int getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     */
    public void setType(int value) {
        this.type = value;
    }

    /**
     * Gets the value of the submitDateTimeYear property.
     * 
     */
    public int getSubmitDateTimeYear() {
        return submitDateTimeYear;
    }

    /**
     * Sets the value of the submitDateTimeYear property.
     * 
     */
    public void setSubmitDateTimeYear(int value) {
        this.submitDateTimeYear = value;
    }

    /**
     * Gets the value of the submitDateTimeMonth property.
     * 
     */
    public int getSubmitDateTimeMonth() {
        return submitDateTimeMonth;
    }

    /**
     * Sets the value of the submitDateTimeMonth property.
     * 
     */
    public void setSubmitDateTimeMonth(int value) {
        this.submitDateTimeMonth = value;
    }

    /**
     * Gets the value of the submitDateTimeDay property.
     * 
     */
    public int getSubmitDateTimeDay() {
        return submitDateTimeDay;
    }

    /**
     * Sets the value of the submitDateTimeDay property.
     * 
     */
    public void setSubmitDateTimeDay(int value) {
        this.submitDateTimeDay = value;
    }

    /**
     * Gets the value of the submitDateTimeHour property.
     * 
     */
    public int getSubmitDateTimeHour() {
        return submitDateTimeHour;
    }

    /**
     * Sets the value of the submitDateTimeHour property.
     * 
     */
    public void setSubmitDateTimeHour(int value) {
        this.submitDateTimeHour = value;
    }

    /**
     * Gets the value of the submitDateTimeMinute property.
     * 
     */
    public int getSubmitDateTimeMinute() {
        return submitDateTimeMinute;
    }

    /**
     * Sets the value of the submitDateTimeMinute property.
     * 
     */
    public void setSubmitDateTimeMinute(int value) {
        this.submitDateTimeMinute = value;
    }

    /**
     * Gets the value of the submitDateTimeSecond property.
     * 
     */
    public int getSubmitDateTimeSecond() {
        return submitDateTimeSecond;
    }

    /**
     * Sets the value of the submitDateTimeSecond property.
     * 
     */
    public void setSubmitDateTimeSecond(int value) {
        this.submitDateTimeSecond = value;
    }

    /**
     * Gets the value of the submitDateTimeMilliSecond property.
     * 
     */
    public int getSubmitDateTimeMilliSecond() {
        return submitDateTimeMilliSecond;
    }

    /**
     * Sets the value of the submitDateTimeMilliSecond property.
     * 
     */
    public void setSubmitDateTimeMilliSecond(int value) {
        this.submitDateTimeMilliSecond = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
