//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Com.MftVanak.EduSys.Ui.Desktop.Win.GheyasManager.GheyasWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GheyasSoap11", Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")]
    public partial class GheyasService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetStudentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTermsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClassesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchStudentsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GheyasService() {
            this.Url = global::Com.MftVanak.EduSys.Ui.Desktop.Win.GheyasManager.Properties.Settings.Default.Com_MftVanak_EduSys_Ui_Desktop_Win_GheyasManager_GheyasWebReference_GheyasService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetStudentsCompletedEventHandler GetStudentsCompleted;
        
        /// <remarks/>
        public event GetTermsCompletedEventHandler GetTermsCompleted;
        
        /// <remarks/>
        public event GetGroupsCompletedEventHandler GetGroupsCompleted;
        
        /// <remarks/>
        public event GetClassesCompletedEventHandler GetClassesCompleted;
        
        /// <remarks/>
        public event SearchStudentsCompletedEventHandler SearchStudentsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetStudentsResponse", Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("GheyasStudents", IsNullable=false)]
        public GheyasStudentType[] GetStudents([System.Xml.Serialization.XmlElementAttribute(Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")] GetStudentsRequest GetStudentsRequest) {
            object[] results = this.Invoke("GetStudents", new object[] {
                        GetStudentsRequest});
            return ((GheyasStudentType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentsAsync(GetStudentsRequest GetStudentsRequest) {
            this.GetStudentsAsync(GetStudentsRequest, null);
        }
        
        /// <remarks/>
        public void GetStudentsAsync(GetStudentsRequest GetStudentsRequest, object userState) {
            if ((this.GetStudentsOperationCompleted == null)) {
                this.GetStudentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentsOperationCompleted);
            }
            this.InvokeAsync("GetStudents", new object[] {
                        GetStudentsRequest}, this.GetStudentsOperationCompleted, userState);
        }
        
        private void OnGetStudentsOperationCompleted(object arg) {
            if ((this.GetStudentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentsCompleted(this, new GetStudentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetTermsResponse", Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("GheyasGroups", IsNullable=false)]
        public GheyasTermType[] GetTerms([System.Xml.Serialization.XmlElementAttribute(Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")] GetTermsRequest GetTermsRequest) {
            object[] results = this.Invoke("GetTerms", new object[] {
                        GetTermsRequest});
            return ((GheyasTermType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTermsAsync(GetTermsRequest GetTermsRequest) {
            this.GetTermsAsync(GetTermsRequest, null);
        }
        
        /// <remarks/>
        public void GetTermsAsync(GetTermsRequest GetTermsRequest, object userState) {
            if ((this.GetTermsOperationCompleted == null)) {
                this.GetTermsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTermsOperationCompleted);
            }
            this.InvokeAsync("GetTerms", new object[] {
                        GetTermsRequest}, this.GetTermsOperationCompleted, userState);
        }
        
        private void OnGetTermsOperationCompleted(object arg) {
            if ((this.GetTermsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTermsCompleted(this, new GetTermsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetGroupsResponse", Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("GheyasGroups", IsNullable=false)]
        public GheyasClassGroupType[] GetGroups([System.Xml.Serialization.XmlElementAttribute(Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")] GetGroupsRequest GetGroupsRequest) {
            object[] results = this.Invoke("GetGroups", new object[] {
                        GetGroupsRequest});
            return ((GheyasClassGroupType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupsAsync(GetGroupsRequest GetGroupsRequest) {
            this.GetGroupsAsync(GetGroupsRequest, null);
        }
        
        /// <remarks/>
        public void GetGroupsAsync(GetGroupsRequest GetGroupsRequest, object userState) {
            if ((this.GetGroupsOperationCompleted == null)) {
                this.GetGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupsOperationCompleted);
            }
            this.InvokeAsync("GetGroups", new object[] {
                        GetGroupsRequest}, this.GetGroupsOperationCompleted, userState);
        }
        
        private void OnGetGroupsOperationCompleted(object arg) {
            if ((this.GetGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupsCompleted(this, new GetGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetClassesResponse", Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("GheyasClasses", IsNullable=false)]
        public GheyasClassType[] GetClasses([System.Xml.Serialization.XmlElementAttribute(Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")] GetClassesRequest GetClassesRequest) {
            object[] results = this.Invoke("GetClasses", new object[] {
                        GetClassesRequest});
            return ((GheyasClassType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetClassesAsync(GetClassesRequest GetClassesRequest) {
            this.GetClassesAsync(GetClassesRequest, null);
        }
        
        /// <remarks/>
        public void GetClassesAsync(GetClassesRequest GetClassesRequest, object userState) {
            if ((this.GetClassesOperationCompleted == null)) {
                this.GetClassesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClassesOperationCompleted);
            }
            this.InvokeAsync("GetClasses", new object[] {
                        GetClassesRequest}, this.GetClassesOperationCompleted, userState);
        }
        
        private void OnGetClassesOperationCompleted(object arg) {
            if ((this.GetClassesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClassesCompleted(this, new GetClassesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("SearchStudentsResponse", Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("GheyasStudents", IsNullable=false)]
        public GheyasStudentType[] SearchStudents([System.Xml.Serialization.XmlElementAttribute(Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")] SearchStudentsRequest SearchStudentsRequest) {
            object[] results = this.Invoke("SearchStudents", new object[] {
                        SearchStudentsRequest});
            return ((GheyasStudentType[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchStudentsAsync(SearchStudentsRequest SearchStudentsRequest) {
            this.SearchStudentsAsync(SearchStudentsRequest, null);
        }
        
        /// <remarks/>
        public void SearchStudentsAsync(SearchStudentsRequest SearchStudentsRequest, object userState) {
            if ((this.SearchStudentsOperationCompleted == null)) {
                this.SearchStudentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchStudentsOperationCompleted);
            }
            this.InvokeAsync("SearchStudents", new object[] {
                        SearchStudentsRequest}, this.SearchStudentsOperationCompleted, userState);
        }
        
        private void OnSearchStudentsOperationCompleted(object arg) {
            if ((this.SearchStudentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchStudentsCompleted(this, new SearchStudentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")]
    public partial class GetStudentsRequest {
        
        private string tokenField;
        
        private string classCodeField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")]
    public partial class GheyasClassType {
        
        private string codeField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string activeDaysField;
        
        private int numberOfStudentsField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ActiveDays {
            get {
                return this.activeDaysField;
            }
            set {
                this.activeDaysField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfStudents {
            get {
                return this.numberOfStudentsField;
            }
            set {
                this.numberOfStudentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")]
    public partial class GheyasClassGroupType {
        
        private string codeField;
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")]
    public partial class GheyasTermType {
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")]
    public partial class GheyasStudentType {
        
        private string codeField;
        
        private string nameField;
        
        private string familyField;
        
        private string birthDateField;
        
        private string addressField;
        
        private string phoneField;
        
        private string emergencyPhoneField;
        
        private string emailField;
        
        private string paidField;
        
        private string paymentField;
        
        private string paymentDateField;
        
        private string paymentDiscountField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Family {
            get {
                return this.familyField;
            }
            set {
                this.familyField = value;
            }
        }
        
        /// <remarks/>
        public string BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string EmergencyPhone {
            get {
                return this.emergencyPhoneField;
            }
            set {
                this.emergencyPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Paid {
            get {
                return this.paidField;
            }
            set {
                this.paidField = value;
            }
        }
        
        /// <remarks/>
        public string Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentDiscount {
            get {
                return this.paymentDiscountField;
            }
            set {
                this.paymentDiscountField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")]
    public partial class GetTermsRequest {
        
        private string tokenField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")]
    public partial class GetGroupsRequest {
        
        private string tokenField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")]
    public partial class GetClassesRequest {
        
        private string tokenField;
        
        private string groupCodeField;
        
        private string termCodeField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string GroupCode {
            get {
                return this.groupCodeField;
            }
            set {
                this.groupCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TermCode {
            get {
                return this.termCodeField;
            }
            set {
                this.termCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gheyas.ws.edusys.mftvanak.com/schemas")]
    public partial class SearchStudentsRequest {
        
        private string tokenField;
        
        private string nameField;
        
        private string familyField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Family {
            get {
                return this.familyField;
            }
            set {
                this.familyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetStudentsCompletedEventHandler(object sender, GetStudentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GheyasStudentType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GheyasStudentType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetTermsCompletedEventHandler(object sender, GetTermsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTermsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTermsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GheyasTermType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GheyasTermType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetGroupsCompletedEventHandler(object sender, GetGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GheyasClassGroupType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GheyasClassGroupType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetClassesCompletedEventHandler(object sender, GetClassesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClassesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClassesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GheyasClassType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GheyasClassType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SearchStudentsCompletedEventHandler(object sender, SearchStudentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchStudentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchStudentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GheyasStudentType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GheyasStudentType[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591