//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Com.MftVanak.EduSys.Ui.Desktop.Win.Apps.ServiceClients.TodoWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TodoSoap11", Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
    public partial class TodoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTodoItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTodoItemsAssignedByPersonOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTodoItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTodoItemsForPersonOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddTodoItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteTodoItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTodoItemByIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TodoService() {
            this.Url = global::Com.MftVanak.EduSys.Ui.Desktop.Win.Apps.ServiceClients.Properties.Settings.Default.Com_MftVanak_EduSys_Ui_Desktop_Win_Apps_ServiceClients_TodoWebReference_TodoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTodoItemsCompletedEventHandler GetTodoItemsCompleted;
        
        /// <remarks/>
        public event GetTodoItemsAssignedByPersonCompletedEventHandler GetTodoItemsAssignedByPersonCompleted;
        
        /// <remarks/>
        public event UpdateTodoItemCompletedEventHandler UpdateTodoItemCompleted;
        
        /// <remarks/>
        public event GetTodoItemsForPersonCompletedEventHandler GetTodoItemsForPersonCompleted;
        
        /// <remarks/>
        public event AddTodoItemCompletedEventHandler AddTodoItemCompleted;
        
        /// <remarks/>
        public event DeleteTodoItemCompletedEventHandler DeleteTodoItemCompleted;
        
        /// <remarks/>
        public event GetTodoItemByIdCompletedEventHandler GetTodoItemByIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetTodoItemsResponse", Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("TodoItems", IsNullable=false)]
        public TodoItemType[] GetTodoItems([System.Xml.Serialization.XmlElementAttribute(Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")] GetTodoItemsRequest GetTodoItemsRequest) {
            object[] results = this.Invoke("GetTodoItems", new object[] {
                        GetTodoItemsRequest});
            return ((TodoItemType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTodoItemsAsync(GetTodoItemsRequest GetTodoItemsRequest) {
            this.GetTodoItemsAsync(GetTodoItemsRequest, null);
        }
        
        /// <remarks/>
        public void GetTodoItemsAsync(GetTodoItemsRequest GetTodoItemsRequest, object userState) {
            if ((this.GetTodoItemsOperationCompleted == null)) {
                this.GetTodoItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTodoItemsOperationCompleted);
            }
            this.InvokeAsync("GetTodoItems", new object[] {
                        GetTodoItemsRequest}, this.GetTodoItemsOperationCompleted, userState);
        }
        
        private void OnGetTodoItemsOperationCompleted(object arg) {
            if ((this.GetTodoItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTodoItemsCompleted(this, new GetTodoItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetTodoItemsAssignedByPersonResponse", Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("TodoItems", IsNullable=false)]
        public TodoItemType[] GetTodoItemsAssignedByPerson([System.Xml.Serialization.XmlElementAttribute(Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")] GetTodoItemsAssignedByPersonRequest GetTodoItemsAssignedByPersonRequest) {
            object[] results = this.Invoke("GetTodoItemsAssignedByPerson", new object[] {
                        GetTodoItemsAssignedByPersonRequest});
            return ((TodoItemType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTodoItemsAssignedByPersonAsync(GetTodoItemsAssignedByPersonRequest GetTodoItemsAssignedByPersonRequest) {
            this.GetTodoItemsAssignedByPersonAsync(GetTodoItemsAssignedByPersonRequest, null);
        }
        
        /// <remarks/>
        public void GetTodoItemsAssignedByPersonAsync(GetTodoItemsAssignedByPersonRequest GetTodoItemsAssignedByPersonRequest, object userState) {
            if ((this.GetTodoItemsAssignedByPersonOperationCompleted == null)) {
                this.GetTodoItemsAssignedByPersonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTodoItemsAssignedByPersonOperationCompleted);
            }
            this.InvokeAsync("GetTodoItemsAssignedByPerson", new object[] {
                        GetTodoItemsAssignedByPersonRequest}, this.GetTodoItemsAssignedByPersonOperationCompleted, userState);
        }
        
        private void OnGetTodoItemsAssignedByPersonOperationCompleted(object arg) {
            if ((this.GetTodoItemsAssignedByPersonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTodoItemsAssignedByPersonCompleted(this, new GetTodoItemsAssignedByPersonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateTodoItemResponse", Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
        public UpdateTodoItemResponse UpdateTodoItem([System.Xml.Serialization.XmlElementAttribute(Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")] UpdateTodoItemRequest UpdateTodoItemRequest) {
            object[] results = this.Invoke("UpdateTodoItem", new object[] {
                        UpdateTodoItemRequest});
            return ((UpdateTodoItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTodoItemAsync(UpdateTodoItemRequest UpdateTodoItemRequest) {
            this.UpdateTodoItemAsync(UpdateTodoItemRequest, null);
        }
        
        /// <remarks/>
        public void UpdateTodoItemAsync(UpdateTodoItemRequest UpdateTodoItemRequest, object userState) {
            if ((this.UpdateTodoItemOperationCompleted == null)) {
                this.UpdateTodoItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTodoItemOperationCompleted);
            }
            this.InvokeAsync("UpdateTodoItem", new object[] {
                        UpdateTodoItemRequest}, this.UpdateTodoItemOperationCompleted, userState);
        }
        
        private void OnUpdateTodoItemOperationCompleted(object arg) {
            if ((this.UpdateTodoItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTodoItemCompleted(this, new UpdateTodoItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetTodoItemsForPersonResponse", Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("TodoItems", IsNullable=false)]
        public TodoItemType[] GetTodoItemsForPerson([System.Xml.Serialization.XmlElementAttribute(Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")] GetTodoItemsForPersonRequest GetTodoItemsForPersonRequest) {
            object[] results = this.Invoke("GetTodoItemsForPerson", new object[] {
                        GetTodoItemsForPersonRequest});
            return ((TodoItemType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTodoItemsForPersonAsync(GetTodoItemsForPersonRequest GetTodoItemsForPersonRequest) {
            this.GetTodoItemsForPersonAsync(GetTodoItemsForPersonRequest, null);
        }
        
        /// <remarks/>
        public void GetTodoItemsForPersonAsync(GetTodoItemsForPersonRequest GetTodoItemsForPersonRequest, object userState) {
            if ((this.GetTodoItemsForPersonOperationCompleted == null)) {
                this.GetTodoItemsForPersonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTodoItemsForPersonOperationCompleted);
            }
            this.InvokeAsync("GetTodoItemsForPerson", new object[] {
                        GetTodoItemsForPersonRequest}, this.GetTodoItemsForPersonOperationCompleted, userState);
        }
        
        private void OnGetTodoItemsForPersonOperationCompleted(object arg) {
            if ((this.GetTodoItemsForPersonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTodoItemsForPersonCompleted(this, new GetTodoItemsForPersonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AddTodoItemResponse", Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
        public AddTodoItemResponse AddTodoItem([System.Xml.Serialization.XmlElementAttribute(Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")] AddTodoItemRequest AddTodoItemRequest) {
            object[] results = this.Invoke("AddTodoItem", new object[] {
                        AddTodoItemRequest});
            return ((AddTodoItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AddTodoItemAsync(AddTodoItemRequest AddTodoItemRequest) {
            this.AddTodoItemAsync(AddTodoItemRequest, null);
        }
        
        /// <remarks/>
        public void AddTodoItemAsync(AddTodoItemRequest AddTodoItemRequest, object userState) {
            if ((this.AddTodoItemOperationCompleted == null)) {
                this.AddTodoItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddTodoItemOperationCompleted);
            }
            this.InvokeAsync("AddTodoItem", new object[] {
                        AddTodoItemRequest}, this.AddTodoItemOperationCompleted, userState);
        }
        
        private void OnAddTodoItemOperationCompleted(object arg) {
            if ((this.AddTodoItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddTodoItemCompleted(this, new AddTodoItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteTodoItemResponse", Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
        public DeleteTodoItemResponse DeleteTodoItem([System.Xml.Serialization.XmlElementAttribute(Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")] DeleteTodoItemRequest DeleteTodoItemRequest) {
            object[] results = this.Invoke("DeleteTodoItem", new object[] {
                        DeleteTodoItemRequest});
            return ((DeleteTodoItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteTodoItemAsync(DeleteTodoItemRequest DeleteTodoItemRequest) {
            this.DeleteTodoItemAsync(DeleteTodoItemRequest, null);
        }
        
        /// <remarks/>
        public void DeleteTodoItemAsync(DeleteTodoItemRequest DeleteTodoItemRequest, object userState) {
            if ((this.DeleteTodoItemOperationCompleted == null)) {
                this.DeleteTodoItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteTodoItemOperationCompleted);
            }
            this.InvokeAsync("DeleteTodoItem", new object[] {
                        DeleteTodoItemRequest}, this.DeleteTodoItemOperationCompleted, userState);
        }
        
        private void OnDeleteTodoItemOperationCompleted(object arg) {
            if ((this.DeleteTodoItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteTodoItemCompleted(this, new DeleteTodoItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetTodoItemByIdResponse", Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
        public GetTodoItemByIdResponse GetTodoItemById([System.Xml.Serialization.XmlElementAttribute(Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")] GetTodoItemByIdRequest GetTodoItemByIdRequest) {
            object[] results = this.Invoke("GetTodoItemById", new object[] {
                        GetTodoItemByIdRequest});
            return ((GetTodoItemByIdResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetTodoItemByIdAsync(GetTodoItemByIdRequest GetTodoItemByIdRequest) {
            this.GetTodoItemByIdAsync(GetTodoItemByIdRequest, null);
        }
        
        /// <remarks/>
        public void GetTodoItemByIdAsync(GetTodoItemByIdRequest GetTodoItemByIdRequest, object userState) {
            if ((this.GetTodoItemByIdOperationCompleted == null)) {
                this.GetTodoItemByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTodoItemByIdOperationCompleted);
            }
            this.InvokeAsync("GetTodoItemById", new object[] {
                        GetTodoItemByIdRequest}, this.GetTodoItemByIdOperationCompleted, userState);
        }
        
        private void OnGetTodoItemByIdOperationCompleted(object arg) {
            if ((this.GetTodoItemByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTodoItemByIdCompleted(this, new GetTodoItemByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
    public partial class GetTodoItemsRequest {
        
        private int clientDateTimeYearField;
        
        private int clientDateTimeMonthField;
        
        private int clientDateTimeDayField;
        
        private int clientDateTimeHourField;
        
        private int clientDateTimeMinuteField;
        
        private int clientDateTimeSecondField;
        
        private int clientDateTimeMilliSecondField;
        
        private string clientMacAddressField;
        
        private string clientIpAddressField;
        
        private string clientComputerNameField;
        
        private string applicationNameField;
        
        private string tokenField;
        
        /// <remarks/>
        public int ClientDateTimeYear {
            get {
                return this.clientDateTimeYearField;
            }
            set {
                this.clientDateTimeYearField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMonth {
            get {
                return this.clientDateTimeMonthField;
            }
            set {
                this.clientDateTimeMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeDay {
            get {
                return this.clientDateTimeDayField;
            }
            set {
                this.clientDateTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeHour {
            get {
                return this.clientDateTimeHourField;
            }
            set {
                this.clientDateTimeHourField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMinute {
            get {
                return this.clientDateTimeMinuteField;
            }
            set {
                this.clientDateTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeSecond {
            get {
                return this.clientDateTimeSecondField;
            }
            set {
                this.clientDateTimeSecondField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMilliSecond {
            get {
                return this.clientDateTimeMilliSecondField;
            }
            set {
                this.clientDateTimeMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientComputerName {
            get {
                return this.clientComputerNameField;
            }
            set {
                this.clientComputerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messaging.ws.edusys.mftvanak.com/schemas/types")]
    public partial class TodoItemType {
        
        private long idField;
        
        private long ownerIdField;
        
        private string ownerFullNameField;
        
        private long receiverIdField;
        
        private string receiverFullNameField;
        
        private bool doneField;
        
        private System.Nullable<ColorType> colorField;
        
        private int priorityField;
        
        private int submitDateYearField;
        
        private int submitDateMonthField;
        
        private int submitDateDayField;
        
        private int submitDateHourField;
        
        private int submitDateMinuteField;
        
        private int submitDateSecondField;
        
        private int submitDateMilliSecondField;
        
        private bool hasDeadlineDateTimeField;
        
        private System.Nullable<int> deadlineDateYearField;
        
        private System.Nullable<int> deadlineDateMonthField;
        
        private System.Nullable<int> deadlineDateDayField;
        
        private System.Nullable<int> deadlineDateHourField;
        
        private System.Nullable<int> deadlineDateMinuteField;
        
        private System.Nullable<int> deadlineDateSecondField;
        
        private System.Nullable<int> deadlineDateMilliSecondField;
        
        private string subjectField;
        
        private string descriptionField;
        
        private string responseField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public long OwnerId {
            get {
                return this.ownerIdField;
            }
            set {
                this.ownerIdField = value;
            }
        }
        
        /// <remarks/>
        public string OwnerFullName {
            get {
                return this.ownerFullNameField;
            }
            set {
                this.ownerFullNameField = value;
            }
        }
        
        /// <remarks/>
        public long ReceiverId {
            get {
                return this.receiverIdField;
            }
            set {
                this.receiverIdField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverFullName {
            get {
                return this.receiverFullNameField;
            }
            set {
                this.receiverFullNameField = value;
            }
        }
        
        /// <remarks/>
        public bool Done {
            get {
                return this.doneField;
            }
            set {
                this.doneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<ColorType> Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public int SubmitDateYear {
            get {
                return this.submitDateYearField;
            }
            set {
                this.submitDateYearField = value;
            }
        }
        
        /// <remarks/>
        public int SubmitDateMonth {
            get {
                return this.submitDateMonthField;
            }
            set {
                this.submitDateMonthField = value;
            }
        }
        
        /// <remarks/>
        public int SubmitDateDay {
            get {
                return this.submitDateDayField;
            }
            set {
                this.submitDateDayField = value;
            }
        }
        
        /// <remarks/>
        public int SubmitDateHour {
            get {
                return this.submitDateHourField;
            }
            set {
                this.submitDateHourField = value;
            }
        }
        
        /// <remarks/>
        public int SubmitDateMinute {
            get {
                return this.submitDateMinuteField;
            }
            set {
                this.submitDateMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int SubmitDateSecond {
            get {
                return this.submitDateSecondField;
            }
            set {
                this.submitDateSecondField = value;
            }
        }
        
        /// <remarks/>
        public int SubmitDateMilliSecond {
            get {
                return this.submitDateMilliSecondField;
            }
            set {
                this.submitDateMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public bool HasDeadlineDateTime {
            get {
                return this.hasDeadlineDateTimeField;
            }
            set {
                this.hasDeadlineDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeadlineDateYear {
            get {
                return this.deadlineDateYearField;
            }
            set {
                this.deadlineDateYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeadlineDateMonth {
            get {
                return this.deadlineDateMonthField;
            }
            set {
                this.deadlineDateMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeadlineDateDay {
            get {
                return this.deadlineDateDayField;
            }
            set {
                this.deadlineDateDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeadlineDateHour {
            get {
                return this.deadlineDateHourField;
            }
            set {
                this.deadlineDateHourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeadlineDateMinute {
            get {
                return this.deadlineDateMinuteField;
            }
            set {
                this.deadlineDateMinuteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeadlineDateSecond {
            get {
                return this.deadlineDateSecondField;
            }
            set {
                this.deadlineDateSecondField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeadlineDateMilliSecond {
            get {
                return this.deadlineDateMilliSecondField;
            }
            set {
                this.deadlineDateMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://messaging.ws.edusys.mftvanak.com/schemas/types")]
    public enum ColorType {
        
        /// <remarks/>
        Blue,
        
        /// <remarks/>
        Green,
        
        /// <remarks/>
        Orange,
        
        /// <remarks/>
        Pink,
        
        /// <remarks/>
        Purple,
        
        /// <remarks/>
        Red,
        
        /// <remarks/>
        Yellow,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
    public partial class GetTodoItemsAssignedByPersonRequest {
        
        private int clientDateTimeYearField;
        
        private int clientDateTimeMonthField;
        
        private int clientDateTimeDayField;
        
        private int clientDateTimeHourField;
        
        private int clientDateTimeMinuteField;
        
        private int clientDateTimeSecondField;
        
        private int clientDateTimeMilliSecondField;
        
        private string clientMacAddressField;
        
        private string clientIpAddressField;
        
        private string clientComputerNameField;
        
        private string applicationNameField;
        
        private string tokenField;
        
        private long personIdField;
        
        private int countField;
        
        /// <remarks/>
        public int ClientDateTimeYear {
            get {
                return this.clientDateTimeYearField;
            }
            set {
                this.clientDateTimeYearField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMonth {
            get {
                return this.clientDateTimeMonthField;
            }
            set {
                this.clientDateTimeMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeDay {
            get {
                return this.clientDateTimeDayField;
            }
            set {
                this.clientDateTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeHour {
            get {
                return this.clientDateTimeHourField;
            }
            set {
                this.clientDateTimeHourField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMinute {
            get {
                return this.clientDateTimeMinuteField;
            }
            set {
                this.clientDateTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeSecond {
            get {
                return this.clientDateTimeSecondField;
            }
            set {
                this.clientDateTimeSecondField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMilliSecond {
            get {
                return this.clientDateTimeMilliSecondField;
            }
            set {
                this.clientDateTimeMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientComputerName {
            get {
                return this.clientComputerNameField;
            }
            set {
                this.clientComputerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public long PersonId {
            get {
                return this.personIdField;
            }
            set {
                this.personIdField = value;
            }
        }
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
    public partial class UpdateTodoItemRequest {
        
        private int clientDateTimeYearField;
        
        private int clientDateTimeMonthField;
        
        private int clientDateTimeDayField;
        
        private int clientDateTimeHourField;
        
        private int clientDateTimeMinuteField;
        
        private int clientDateTimeSecondField;
        
        private int clientDateTimeMilliSecondField;
        
        private string clientMacAddressField;
        
        private string clientIpAddressField;
        
        private string clientComputerNameField;
        
        private string applicationNameField;
        
        private string tokenField;
        
        private TodoItemType todoItemField;
        
        /// <remarks/>
        public int ClientDateTimeYear {
            get {
                return this.clientDateTimeYearField;
            }
            set {
                this.clientDateTimeYearField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMonth {
            get {
                return this.clientDateTimeMonthField;
            }
            set {
                this.clientDateTimeMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeDay {
            get {
                return this.clientDateTimeDayField;
            }
            set {
                this.clientDateTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeHour {
            get {
                return this.clientDateTimeHourField;
            }
            set {
                this.clientDateTimeHourField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMinute {
            get {
                return this.clientDateTimeMinuteField;
            }
            set {
                this.clientDateTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeSecond {
            get {
                return this.clientDateTimeSecondField;
            }
            set {
                this.clientDateTimeSecondField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMilliSecond {
            get {
                return this.clientDateTimeMilliSecondField;
            }
            set {
                this.clientDateTimeMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientComputerName {
            get {
                return this.clientComputerNameField;
            }
            set {
                this.clientComputerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public TodoItemType TodoItem {
            get {
                return this.todoItemField;
            }
            set {
                this.todoItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
    public partial class UpdateTodoItemResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
    public partial class GetTodoItemsForPersonRequest {
        
        private int clientDateTimeYearField;
        
        private int clientDateTimeMonthField;
        
        private int clientDateTimeDayField;
        
        private int clientDateTimeHourField;
        
        private int clientDateTimeMinuteField;
        
        private int clientDateTimeSecondField;
        
        private int clientDateTimeMilliSecondField;
        
        private string clientMacAddressField;
        
        private string clientIpAddressField;
        
        private string clientComputerNameField;
        
        private string applicationNameField;
        
        private string tokenField;
        
        private long personIdField;
        
        private int countField;
        
        /// <remarks/>
        public int ClientDateTimeYear {
            get {
                return this.clientDateTimeYearField;
            }
            set {
                this.clientDateTimeYearField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMonth {
            get {
                return this.clientDateTimeMonthField;
            }
            set {
                this.clientDateTimeMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeDay {
            get {
                return this.clientDateTimeDayField;
            }
            set {
                this.clientDateTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeHour {
            get {
                return this.clientDateTimeHourField;
            }
            set {
                this.clientDateTimeHourField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMinute {
            get {
                return this.clientDateTimeMinuteField;
            }
            set {
                this.clientDateTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeSecond {
            get {
                return this.clientDateTimeSecondField;
            }
            set {
                this.clientDateTimeSecondField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMilliSecond {
            get {
                return this.clientDateTimeMilliSecondField;
            }
            set {
                this.clientDateTimeMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientComputerName {
            get {
                return this.clientComputerNameField;
            }
            set {
                this.clientComputerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public long PersonId {
            get {
                return this.personIdField;
            }
            set {
                this.personIdField = value;
            }
        }
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
    public partial class AddTodoItemRequest {
        
        private int clientDateTimeYearField;
        
        private int clientDateTimeMonthField;
        
        private int clientDateTimeDayField;
        
        private int clientDateTimeHourField;
        
        private int clientDateTimeMinuteField;
        
        private int clientDateTimeSecondField;
        
        private int clientDateTimeMilliSecondField;
        
        private string clientMacAddressField;
        
        private string clientIpAddressField;
        
        private string clientComputerNameField;
        
        private string applicationNameField;
        
        private string tokenField;
        
        private TodoItemType todoItemField;
        
        /// <remarks/>
        public int ClientDateTimeYear {
            get {
                return this.clientDateTimeYearField;
            }
            set {
                this.clientDateTimeYearField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMonth {
            get {
                return this.clientDateTimeMonthField;
            }
            set {
                this.clientDateTimeMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeDay {
            get {
                return this.clientDateTimeDayField;
            }
            set {
                this.clientDateTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeHour {
            get {
                return this.clientDateTimeHourField;
            }
            set {
                this.clientDateTimeHourField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMinute {
            get {
                return this.clientDateTimeMinuteField;
            }
            set {
                this.clientDateTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeSecond {
            get {
                return this.clientDateTimeSecondField;
            }
            set {
                this.clientDateTimeSecondField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMilliSecond {
            get {
                return this.clientDateTimeMilliSecondField;
            }
            set {
                this.clientDateTimeMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientComputerName {
            get {
                return this.clientComputerNameField;
            }
            set {
                this.clientComputerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public TodoItemType TodoItem {
            get {
                return this.todoItemField;
            }
            set {
                this.todoItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
    public partial class AddTodoItemResponse {
        
        private long todoItemIdField;
        
        /// <remarks/>
        public long TodoItemId {
            get {
                return this.todoItemIdField;
            }
            set {
                this.todoItemIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
    public partial class DeleteTodoItemRequest {
        
        private int clientDateTimeYearField;
        
        private int clientDateTimeMonthField;
        
        private int clientDateTimeDayField;
        
        private int clientDateTimeHourField;
        
        private int clientDateTimeMinuteField;
        
        private int clientDateTimeSecondField;
        
        private int clientDateTimeMilliSecondField;
        
        private string clientMacAddressField;
        
        private string clientIpAddressField;
        
        private string clientComputerNameField;
        
        private string applicationNameField;
        
        private string tokenField;
        
        private long todoItemIdField;
        
        /// <remarks/>
        public int ClientDateTimeYear {
            get {
                return this.clientDateTimeYearField;
            }
            set {
                this.clientDateTimeYearField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMonth {
            get {
                return this.clientDateTimeMonthField;
            }
            set {
                this.clientDateTimeMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeDay {
            get {
                return this.clientDateTimeDayField;
            }
            set {
                this.clientDateTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeHour {
            get {
                return this.clientDateTimeHourField;
            }
            set {
                this.clientDateTimeHourField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMinute {
            get {
                return this.clientDateTimeMinuteField;
            }
            set {
                this.clientDateTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeSecond {
            get {
                return this.clientDateTimeSecondField;
            }
            set {
                this.clientDateTimeSecondField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMilliSecond {
            get {
                return this.clientDateTimeMilliSecondField;
            }
            set {
                this.clientDateTimeMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientComputerName {
            get {
                return this.clientComputerNameField;
            }
            set {
                this.clientComputerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public long TodoItemId {
            get {
                return this.todoItemIdField;
            }
            set {
                this.todoItemIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
    public partial class DeleteTodoItemResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
    public partial class GetTodoItemByIdRequest {
        
        private int clientDateTimeYearField;
        
        private int clientDateTimeMonthField;
        
        private int clientDateTimeDayField;
        
        private int clientDateTimeHourField;
        
        private int clientDateTimeMinuteField;
        
        private int clientDateTimeSecondField;
        
        private int clientDateTimeMilliSecondField;
        
        private string clientMacAddressField;
        
        private string clientIpAddressField;
        
        private string clientComputerNameField;
        
        private string applicationNameField;
        
        private string tokenField;
        
        private long todoItemIdField;
        
        /// <remarks/>
        public int ClientDateTimeYear {
            get {
                return this.clientDateTimeYearField;
            }
            set {
                this.clientDateTimeYearField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMonth {
            get {
                return this.clientDateTimeMonthField;
            }
            set {
                this.clientDateTimeMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeDay {
            get {
                return this.clientDateTimeDayField;
            }
            set {
                this.clientDateTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeHour {
            get {
                return this.clientDateTimeHourField;
            }
            set {
                this.clientDateTimeHourField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMinute {
            get {
                return this.clientDateTimeMinuteField;
            }
            set {
                this.clientDateTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeSecond {
            get {
                return this.clientDateTimeSecondField;
            }
            set {
                this.clientDateTimeSecondField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMilliSecond {
            get {
                return this.clientDateTimeMilliSecondField;
            }
            set {
                this.clientDateTimeMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientComputerName {
            get {
                return this.clientComputerNameField;
            }
            set {
                this.clientComputerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public long TodoItemId {
            get {
                return this.todoItemIdField;
            }
            set {
                this.todoItemIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://messaging.ws.edusys.mftvanak.com/schemas")]
    public partial class GetTodoItemByIdResponse {
        
        private TodoItemType todoItemField;
        
        /// <remarks/>
        public TodoItemType TodoItem {
            get {
                return this.todoItemField;
            }
            set {
                this.todoItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetTodoItemsCompletedEventHandler(object sender, GetTodoItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTodoItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTodoItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TodoItemType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TodoItemType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetTodoItemsAssignedByPersonCompletedEventHandler(object sender, GetTodoItemsAssignedByPersonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTodoItemsAssignedByPersonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTodoItemsAssignedByPersonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TodoItemType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TodoItemType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateTodoItemCompletedEventHandler(object sender, UpdateTodoItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTodoItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTodoItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateTodoItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateTodoItemResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetTodoItemsForPersonCompletedEventHandler(object sender, GetTodoItemsForPersonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTodoItemsForPersonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTodoItemsForPersonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TodoItemType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TodoItemType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddTodoItemCompletedEventHandler(object sender, AddTodoItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddTodoItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddTodoItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddTodoItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddTodoItemResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteTodoItemCompletedEventHandler(object sender, DeleteTodoItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteTodoItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteTodoItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteTodoItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteTodoItemResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetTodoItemByIdCompletedEventHandler(object sender, GetTodoItemByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTodoItemByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTodoItemByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetTodoItemByIdResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetTodoItemByIdResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591