//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.03 at 02:30:04 AM IRDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://portal.ws.edusys.mftvanak.com/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mftvanak.edusys.ws.portal.schemas;
