//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Com.MftVanak.EduSys.Ui.Desktop.Win.Apps.ServiceClients.ReservationWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReservationServiceSoap11", Namespace="http://education.ws.edusys.mftvanak.com/schemas/reservation")]
    public partial class ReservationServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCmsReservationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCmsGeneralReservationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCmsGeneralReservationOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCmsReservationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ReservationServiceService() {
            this.Url = global::Com.MftVanak.EduSys.Ui.Desktop.Win.Apps.ServiceClients.Properties.Settings.Default.Com_MftVanak_EduSys_Ui_Desktop_Win_Apps_ServiceClients_ReservationWebReference_ReservationServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCmsReservationsCompletedEventHandler GetCmsReservationsCompleted;
        
        /// <remarks/>
        public event GetCmsGeneralReservationsCompletedEventHandler GetCmsGeneralReservationsCompleted;
        
        /// <remarks/>
        public event UpdateCmsGeneralReservationCompletedEventHandler UpdateCmsGeneralReservationCompleted;
        
        /// <remarks/>
        public event UpdateCmsReservationCompletedEventHandler UpdateCmsReservationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetCmsReservationsResponse", Namespace="http://education.ws.edusys.mftvanak.com/schemas/reservation")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("CmsReservations", IsNullable=false)]
        public CmsReservationType[] GetCmsReservations([System.Xml.Serialization.XmlElementAttribute(Namespace="http://education.ws.edusys.mftvanak.com/schemas/reservation")] GetCmsReservationsRequest GetCmsReservationsRequest) {
            object[] results = this.Invoke("GetCmsReservations", new object[] {
                        GetCmsReservationsRequest});
            return ((CmsReservationType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCmsReservationsAsync(GetCmsReservationsRequest GetCmsReservationsRequest) {
            this.GetCmsReservationsAsync(GetCmsReservationsRequest, null);
        }
        
        /// <remarks/>
        public void GetCmsReservationsAsync(GetCmsReservationsRequest GetCmsReservationsRequest, object userState) {
            if ((this.GetCmsReservationsOperationCompleted == null)) {
                this.GetCmsReservationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCmsReservationsOperationCompleted);
            }
            this.InvokeAsync("GetCmsReservations", new object[] {
                        GetCmsReservationsRequest}, this.GetCmsReservationsOperationCompleted, userState);
        }
        
        private void OnGetCmsReservationsOperationCompleted(object arg) {
            if ((this.GetCmsReservationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCmsReservationsCompleted(this, new GetCmsReservationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetCmsGeneralReservationsResponse", Namespace="http://education.ws.edusys.mftvanak.com/schemas/reservation")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("CmsGeneralReservations", IsNullable=false)]
        public CmsGeneralReservationType[] GetCmsGeneralReservations([System.Xml.Serialization.XmlElementAttribute(Namespace="http://education.ws.edusys.mftvanak.com/schemas/reservation")] GetCmsGeneralReservationsRequest GetCmsGeneralReservationsRequest) {
            object[] results = this.Invoke("GetCmsGeneralReservations", new object[] {
                        GetCmsGeneralReservationsRequest});
            return ((CmsGeneralReservationType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCmsGeneralReservationsAsync(GetCmsGeneralReservationsRequest GetCmsGeneralReservationsRequest) {
            this.GetCmsGeneralReservationsAsync(GetCmsGeneralReservationsRequest, null);
        }
        
        /// <remarks/>
        public void GetCmsGeneralReservationsAsync(GetCmsGeneralReservationsRequest GetCmsGeneralReservationsRequest, object userState) {
            if ((this.GetCmsGeneralReservationsOperationCompleted == null)) {
                this.GetCmsGeneralReservationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCmsGeneralReservationsOperationCompleted);
            }
            this.InvokeAsync("GetCmsGeneralReservations", new object[] {
                        GetCmsGeneralReservationsRequest}, this.GetCmsGeneralReservationsOperationCompleted, userState);
        }
        
        private void OnGetCmsGeneralReservationsOperationCompleted(object arg) {
            if ((this.GetCmsGeneralReservationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCmsGeneralReservationsCompleted(this, new GetCmsGeneralReservationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateCmsGeneralReservationResponse", Namespace="http://education.ws.edusys.mftvanak.com/schemas/reservation")]
        public UpdateCmsGeneralReservationResponse UpdateCmsGeneralReservation([System.Xml.Serialization.XmlElementAttribute(Namespace="http://education.ws.edusys.mftvanak.com/schemas/reservation")] UpdateCmsGeneralReservationRequest UpdateCmsGeneralReservationRequest) {
            object[] results = this.Invoke("UpdateCmsGeneralReservation", new object[] {
                        UpdateCmsGeneralReservationRequest});
            return ((UpdateCmsGeneralReservationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCmsGeneralReservationAsync(UpdateCmsGeneralReservationRequest UpdateCmsGeneralReservationRequest) {
            this.UpdateCmsGeneralReservationAsync(UpdateCmsGeneralReservationRequest, null);
        }
        
        /// <remarks/>
        public void UpdateCmsGeneralReservationAsync(UpdateCmsGeneralReservationRequest UpdateCmsGeneralReservationRequest, object userState) {
            if ((this.UpdateCmsGeneralReservationOperationCompleted == null)) {
                this.UpdateCmsGeneralReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCmsGeneralReservationOperationCompleted);
            }
            this.InvokeAsync("UpdateCmsGeneralReservation", new object[] {
                        UpdateCmsGeneralReservationRequest}, this.UpdateCmsGeneralReservationOperationCompleted, userState);
        }
        
        private void OnUpdateCmsGeneralReservationOperationCompleted(object arg) {
            if ((this.UpdateCmsGeneralReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCmsGeneralReservationCompleted(this, new UpdateCmsGeneralReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateCmsReservationResponse", Namespace="http://education.ws.edusys.mftvanak.com/schemas/reservation")]
        public UpdateCmsReservationResponse UpdateCmsReservation([System.Xml.Serialization.XmlElementAttribute(Namespace="http://education.ws.edusys.mftvanak.com/schemas/reservation")] UpdateCmsReservationRequest UpdateCmsReservationRequest) {
            object[] results = this.Invoke("UpdateCmsReservation", new object[] {
                        UpdateCmsReservationRequest});
            return ((UpdateCmsReservationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCmsReservationAsync(UpdateCmsReservationRequest UpdateCmsReservationRequest) {
            this.UpdateCmsReservationAsync(UpdateCmsReservationRequest, null);
        }
        
        /// <remarks/>
        public void UpdateCmsReservationAsync(UpdateCmsReservationRequest UpdateCmsReservationRequest, object userState) {
            if ((this.UpdateCmsReservationOperationCompleted == null)) {
                this.UpdateCmsReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCmsReservationOperationCompleted);
            }
            this.InvokeAsync("UpdateCmsReservation", new object[] {
                        UpdateCmsReservationRequest}, this.UpdateCmsReservationOperationCompleted, userState);
        }
        
        private void OnUpdateCmsReservationOperationCompleted(object arg) {
            if ((this.UpdateCmsReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCmsReservationCompleted(this, new UpdateCmsReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://education.ws.edusys.mftvanak.com/schemas/reservation")]
    public partial class GetCmsReservationsRequest {
        
        private int clientDateTimeYearField;
        
        private int clientDateTimeMonthField;
        
        private int clientDateTimeDayField;
        
        private int clientDateTimeHourField;
        
        private int clientDateTimeMinuteField;
        
        private int clientDateTimeSecondField;
        
        private int clientDateTimeMilliSecondField;
        
        private string clientMacAddressField;
        
        private string clientIpAddressField;
        
        private string clientComputerNameField;
        
        private string applicationNameField;
        
        private string tokenField;
        
        private long departmentIdField;
        
        private long reservationPlanIdField;
        
        private System.Nullable<int> countField;
        
        /// <remarks/>
        public int ClientDateTimeYear {
            get {
                return this.clientDateTimeYearField;
            }
            set {
                this.clientDateTimeYearField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMonth {
            get {
                return this.clientDateTimeMonthField;
            }
            set {
                this.clientDateTimeMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeDay {
            get {
                return this.clientDateTimeDayField;
            }
            set {
                this.clientDateTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeHour {
            get {
                return this.clientDateTimeHourField;
            }
            set {
                this.clientDateTimeHourField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMinute {
            get {
                return this.clientDateTimeMinuteField;
            }
            set {
                this.clientDateTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeSecond {
            get {
                return this.clientDateTimeSecondField;
            }
            set {
                this.clientDateTimeSecondField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMilliSecond {
            get {
                return this.clientDateTimeMilliSecondField;
            }
            set {
                this.clientDateTimeMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientComputerName {
            get {
                return this.clientComputerNameField;
            }
            set {
                this.clientComputerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public long DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
        
        /// <remarks/>
        public long ReservationPlanId {
            get {
                return this.reservationPlanIdField;
            }
            set {
                this.reservationPlanIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://education.ws.edusys.mftvanak.com/schemas/types")]
    public partial class CmsGeneralReservationType {
        
        private long idField;
        
        private System.Nullable<bool> willRegisterField;
        
        private System.Nullable<bool> willRegisterWithConditionField;
        
        private System.Nullable<bool> cancelledField;
        
        private System.Nullable<bool> notAnsweredField;
        
        private System.Nullable<bool> followedField;
        
        private System.Nullable<bool> willInformUsField;
        
        private System.Nullable<bool> hasRegisteredField;
        
        private bool seenField;
        
        private bool calledField;
        
        private bool smsSentField;
        
        private long cmsDepartmentIdField;
        
        private string cmsDepartmentNameField;
        
        private long cmsGroupIdField;
        
        private string cmsGroupNameField;
        
        private long cmsClassIdField;
        
        private string cmsClassNameField;
        
        private long calculatedDateField;
        
        private string dateField;
        
        private string nameField;
        
        private string emailField;
        
        private string phoneField;
        
        private string textField;
        
        private string descriptionField;
        
        private string sourceField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> WillRegister {
            get {
                return this.willRegisterField;
            }
            set {
                this.willRegisterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> WillRegisterWithCondition {
            get {
                return this.willRegisterWithConditionField;
            }
            set {
                this.willRegisterWithConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Cancelled {
            get {
                return this.cancelledField;
            }
            set {
                this.cancelledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> NotAnswered {
            get {
                return this.notAnsweredField;
            }
            set {
                this.notAnsweredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Followed {
            get {
                return this.followedField;
            }
            set {
                this.followedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> WillInformUs {
            get {
                return this.willInformUsField;
            }
            set {
                this.willInformUsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> HasRegistered {
            get {
                return this.hasRegisteredField;
            }
            set {
                this.hasRegisteredField = value;
            }
        }
        
        /// <remarks/>
        public bool Seen {
            get {
                return this.seenField;
            }
            set {
                this.seenField = value;
            }
        }
        
        /// <remarks/>
        public bool Called {
            get {
                return this.calledField;
            }
            set {
                this.calledField = value;
            }
        }
        
        /// <remarks/>
        public bool SmsSent {
            get {
                return this.smsSentField;
            }
            set {
                this.smsSentField = value;
            }
        }
        
        /// <remarks/>
        public long CmsDepartmentId {
            get {
                return this.cmsDepartmentIdField;
            }
            set {
                this.cmsDepartmentIdField = value;
            }
        }
        
        /// <remarks/>
        public string CmsDepartmentName {
            get {
                return this.cmsDepartmentNameField;
            }
            set {
                this.cmsDepartmentNameField = value;
            }
        }
        
        /// <remarks/>
        public long CmsGroupId {
            get {
                return this.cmsGroupIdField;
            }
            set {
                this.cmsGroupIdField = value;
            }
        }
        
        /// <remarks/>
        public string CmsGroupName {
            get {
                return this.cmsGroupNameField;
            }
            set {
                this.cmsGroupNameField = value;
            }
        }
        
        /// <remarks/>
        public long CmsClassId {
            get {
                return this.cmsClassIdField;
            }
            set {
                this.cmsClassIdField = value;
            }
        }
        
        /// <remarks/>
        public string CmsClassName {
            get {
                return this.cmsClassNameField;
            }
            set {
                this.cmsClassNameField = value;
            }
        }
        
        /// <remarks/>
        public long CalculatedDate {
            get {
                return this.calculatedDateField;
            }
            set {
                this.calculatedDateField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://education.ws.edusys.mftvanak.com/schemas/types")]
    public partial class CmsReservationType {
        
        private long idField;
        
        private System.Nullable<bool> willRegisterField;
        
        private System.Nullable<bool> willRegisterWithConditionField;
        
        private System.Nullable<bool> cancelledField;
        
        private System.Nullable<bool> notAnsweredField;
        
        private System.Nullable<bool> followedField;
        
        private System.Nullable<bool> willInformUsField;
        
        private System.Nullable<bool> hasRegisteredField;
        
        private bool seenField;
        
        private bool calledField;
        
        private bool smsSentField;
        
        private long cmsDepartmentIdField;
        
        private string cmsDepartmentNameField;
        
        private long calculatedDateField;
        
        private string dateField;
        
        private string nameField;
        
        private string emailField;
        
        private string phoneField;
        
        private string textField;
        
        private string timeField;
        
        private string descriptionField;
        
        private string sourceField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> WillRegister {
            get {
                return this.willRegisterField;
            }
            set {
                this.willRegisterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> WillRegisterWithCondition {
            get {
                return this.willRegisterWithConditionField;
            }
            set {
                this.willRegisterWithConditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Cancelled {
            get {
                return this.cancelledField;
            }
            set {
                this.cancelledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> NotAnswered {
            get {
                return this.notAnsweredField;
            }
            set {
                this.notAnsweredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Followed {
            get {
                return this.followedField;
            }
            set {
                this.followedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> WillInformUs {
            get {
                return this.willInformUsField;
            }
            set {
                this.willInformUsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> HasRegistered {
            get {
                return this.hasRegisteredField;
            }
            set {
                this.hasRegisteredField = value;
            }
        }
        
        /// <remarks/>
        public bool Seen {
            get {
                return this.seenField;
            }
            set {
                this.seenField = value;
            }
        }
        
        /// <remarks/>
        public bool Called {
            get {
                return this.calledField;
            }
            set {
                this.calledField = value;
            }
        }
        
        /// <remarks/>
        public bool SmsSent {
            get {
                return this.smsSentField;
            }
            set {
                this.smsSentField = value;
            }
        }
        
        /// <remarks/>
        public long CmsDepartmentId {
            get {
                return this.cmsDepartmentIdField;
            }
            set {
                this.cmsDepartmentIdField = value;
            }
        }
        
        /// <remarks/>
        public string CmsDepartmentName {
            get {
                return this.cmsDepartmentNameField;
            }
            set {
                this.cmsDepartmentNameField = value;
            }
        }
        
        /// <remarks/>
        public long CalculatedDate {
            get {
                return this.calculatedDateField;
            }
            set {
                this.calculatedDateField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://education.ws.edusys.mftvanak.com/schemas/reservation")]
    public partial class GetCmsGeneralReservationsRequest {
        
        private int clientDateTimeYearField;
        
        private int clientDateTimeMonthField;
        
        private int clientDateTimeDayField;
        
        private int clientDateTimeHourField;
        
        private int clientDateTimeMinuteField;
        
        private int clientDateTimeSecondField;
        
        private int clientDateTimeMilliSecondField;
        
        private string clientMacAddressField;
        
        private string clientIpAddressField;
        
        private string clientComputerNameField;
        
        private string applicationNameField;
        
        private string tokenField;
        
        private long departmentIdField;
        
        private System.Nullable<long> groupIdField;
        
        private System.Nullable<long> classIdField;
        
        private System.Nullable<int> countField;
        
        /// <remarks/>
        public int ClientDateTimeYear {
            get {
                return this.clientDateTimeYearField;
            }
            set {
                this.clientDateTimeYearField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMonth {
            get {
                return this.clientDateTimeMonthField;
            }
            set {
                this.clientDateTimeMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeDay {
            get {
                return this.clientDateTimeDayField;
            }
            set {
                this.clientDateTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeHour {
            get {
                return this.clientDateTimeHourField;
            }
            set {
                this.clientDateTimeHourField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMinute {
            get {
                return this.clientDateTimeMinuteField;
            }
            set {
                this.clientDateTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeSecond {
            get {
                return this.clientDateTimeSecondField;
            }
            set {
                this.clientDateTimeSecondField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMilliSecond {
            get {
                return this.clientDateTimeMilliSecondField;
            }
            set {
                this.clientDateTimeMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientComputerName {
            get {
                return this.clientComputerNameField;
            }
            set {
                this.clientComputerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public long DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> GroupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> ClassId {
            get {
                return this.classIdField;
            }
            set {
                this.classIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://education.ws.edusys.mftvanak.com/schemas/reservation")]
    public partial class UpdateCmsGeneralReservationRequest {
        
        private int clientDateTimeYearField;
        
        private int clientDateTimeMonthField;
        
        private int clientDateTimeDayField;
        
        private int clientDateTimeHourField;
        
        private int clientDateTimeMinuteField;
        
        private int clientDateTimeSecondField;
        
        private int clientDateTimeMilliSecondField;
        
        private string clientMacAddressField;
        
        private string clientIpAddressField;
        
        private string clientComputerNameField;
        
        private string applicationNameField;
        
        private string tokenField;
        
        private CmsGeneralReservationType cmsGeneralReservationField;
        
        /// <remarks/>
        public int ClientDateTimeYear {
            get {
                return this.clientDateTimeYearField;
            }
            set {
                this.clientDateTimeYearField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMonth {
            get {
                return this.clientDateTimeMonthField;
            }
            set {
                this.clientDateTimeMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeDay {
            get {
                return this.clientDateTimeDayField;
            }
            set {
                this.clientDateTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeHour {
            get {
                return this.clientDateTimeHourField;
            }
            set {
                this.clientDateTimeHourField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMinute {
            get {
                return this.clientDateTimeMinuteField;
            }
            set {
                this.clientDateTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeSecond {
            get {
                return this.clientDateTimeSecondField;
            }
            set {
                this.clientDateTimeSecondField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMilliSecond {
            get {
                return this.clientDateTimeMilliSecondField;
            }
            set {
                this.clientDateTimeMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientComputerName {
            get {
                return this.clientComputerNameField;
            }
            set {
                this.clientComputerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public CmsGeneralReservationType CmsGeneralReservation {
            get {
                return this.cmsGeneralReservationField;
            }
            set {
                this.cmsGeneralReservationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://education.ws.edusys.mftvanak.com/schemas/reservation")]
    public partial class UpdateCmsGeneralReservationResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://education.ws.edusys.mftvanak.com/schemas/reservation")]
    public partial class UpdateCmsReservationRequest {
        
        private int clientDateTimeYearField;
        
        private int clientDateTimeMonthField;
        
        private int clientDateTimeDayField;
        
        private int clientDateTimeHourField;
        
        private int clientDateTimeMinuteField;
        
        private int clientDateTimeSecondField;
        
        private int clientDateTimeMilliSecondField;
        
        private string clientMacAddressField;
        
        private string clientIpAddressField;
        
        private string clientComputerNameField;
        
        private string applicationNameField;
        
        private string tokenField;
        
        private CmsReservationType cmsReservationField;
        
        /// <remarks/>
        public int ClientDateTimeYear {
            get {
                return this.clientDateTimeYearField;
            }
            set {
                this.clientDateTimeYearField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMonth {
            get {
                return this.clientDateTimeMonthField;
            }
            set {
                this.clientDateTimeMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeDay {
            get {
                return this.clientDateTimeDayField;
            }
            set {
                this.clientDateTimeDayField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeHour {
            get {
                return this.clientDateTimeHourField;
            }
            set {
                this.clientDateTimeHourField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMinute {
            get {
                return this.clientDateTimeMinuteField;
            }
            set {
                this.clientDateTimeMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeSecond {
            get {
                return this.clientDateTimeSecondField;
            }
            set {
                this.clientDateTimeSecondField = value;
            }
        }
        
        /// <remarks/>
        public int ClientDateTimeMilliSecond {
            get {
                return this.clientDateTimeMilliSecondField;
            }
            set {
                this.clientDateTimeMilliSecondField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMacAddress {
            get {
                return this.clientMacAddressField;
            }
            set {
                this.clientMacAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientIpAddress {
            get {
                return this.clientIpAddressField;
            }
            set {
                this.clientIpAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientComputerName {
            get {
                return this.clientComputerNameField;
            }
            set {
                this.clientComputerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public CmsReservationType CmsReservation {
            get {
                return this.cmsReservationField;
            }
            set {
                this.cmsReservationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://education.ws.edusys.mftvanak.com/schemas/reservation")]
    public partial class UpdateCmsReservationResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCmsReservationsCompletedEventHandler(object sender, GetCmsReservationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCmsReservationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCmsReservationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CmsReservationType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CmsReservationType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCmsGeneralReservationsCompletedEventHandler(object sender, GetCmsGeneralReservationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCmsGeneralReservationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCmsGeneralReservationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CmsGeneralReservationType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CmsGeneralReservationType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateCmsGeneralReservationCompletedEventHandler(object sender, UpdateCmsGeneralReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCmsGeneralReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCmsGeneralReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateCmsGeneralReservationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateCmsGeneralReservationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateCmsReservationCompletedEventHandler(object sender, UpdateCmsReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCmsReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCmsReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateCmsReservationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateCmsReservationResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591