//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.09.19 at 12:45:05 AM IRDT
//

package com.mftvanak.edusys.ws.education.schemas.department;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DepartmentId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType (XmlAccessType.FIELD)
@XmlType (name = "", propOrder = {"departmentId"})
@XmlRootElement (name = "AddDepartmentResponse")
public class AddDepartmentResponse {

  @XmlElement (name = "DepartmentId")
  protected long departmentId;

  /**
   * Gets the value of the departmentId property.
   * 
   */
  public long getDepartmentId () {
    return departmentId;
  }

  /**
   * Sets the value of the departmentId property.
   * 
   */
  public void setDepartmentId (long value) {
    this.departmentId = value;
  }

}
