//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.16 at 11:21:08 AM IRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://authentication.ws.edusys.mftvanak.com/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mftvanak.edusys.ws.authentication.schemas;
