//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.12 at 01:52:53 AM IRST
//

package com.mftvanak.edusys.ws.education.schemas.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for InstituteType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="InstituteType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="PersianName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EnglishName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Phone1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Phone2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FaxNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Email1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Email2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WebUrl1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WebUrl2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType (XmlAccessType.FIELD)
@XmlType (name = "InstituteType", propOrder = {

})
public class InstituteType {

  @XmlElement (name = "Id")
  protected long id;
  @XmlElement (name = "PersianName", required = true)
  protected String persianName;
  @XmlElement (name = "EnglishName", required = true)
  protected String englishName;
  @XmlElement (name = "Phone1", required = true)
  protected String phone1;
  @XmlElement (name = "Phone2", required = true)
  protected String phone2;
  @XmlElement (name = "FaxNumber", required = true)
  protected String faxNumber;
  @XmlElement (name = "Email1", required = true)
  protected String email1;
  @XmlElement (name = "Email2", required = true)
  protected String email2;
  @XmlElement (name = "WebUrl1", required = true)
  protected String webUrl1;
  @XmlElement (name = "WebUrl2", required = true)
  protected String webUrl2;

  /**
   * Gets the value of the id property.
   * 
   */
  public long getId () {
    return id;
  }

  /**
   * Sets the value of the id property.
   * 
   */
  public void setId (long value) {
    this.id = value;
  }

  /**
   * Gets the value of the persianName property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getPersianName () {
    return persianName;
  }

  /**
   * Sets the value of the persianName property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setPersianName (String value) {
    this.persianName = value;
  }

  /**
   * Gets the value of the englishName property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getEnglishName () {
    return englishName;
  }

  /**
   * Sets the value of the englishName property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setEnglishName (String value) {
    this.englishName = value;
  }

  /**
   * Gets the value of the phone1 property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getPhone1 () {
    return phone1;
  }

  /**
   * Sets the value of the phone1 property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setPhone1 (String value) {
    this.phone1 = value;
  }

  /**
   * Gets the value of the phone2 property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getPhone2 () {
    return phone2;
  }

  /**
   * Sets the value of the phone2 property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setPhone2 (String value) {
    this.phone2 = value;
  }

  /**
   * Gets the value of the faxNumber property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getFaxNumber () {
    return faxNumber;
  }

  /**
   * Sets the value of the faxNumber property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setFaxNumber (String value) {
    this.faxNumber = value;
  }

  /**
   * Gets the value of the email1 property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getEmail1 () {
    return email1;
  }

  /**
   * Sets the value of the email1 property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setEmail1 (String value) {
    this.email1 = value;
  }

  /**
   * Gets the value of the email2 property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getEmail2 () {
    return email2;
  }

  /**
   * Sets the value of the email2 property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setEmail2 (String value) {
    this.email2 = value;
  }

  /**
   * Gets the value of the webUrl1 property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getWebUrl1 () {
    return webUrl1;
  }

  /**
   * Sets the value of the webUrl1 property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setWebUrl1 (String value) {
    this.webUrl1 = value;
  }

  /**
   * Gets the value of the webUrl2 property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getWebUrl2 () {
    return webUrl2;
  }

  /**
   * Sets the value of the webUrl2 property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setWebUrl2 (String value) {
    this.webUrl2 = value;
  }

}
