//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.12 at 01:52:53 AM IRST
//

package com.mftvanak.edusys.ws.education.schemas.types;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * com.mftvanak.edusys.ws.education.schemas.types package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

  /**
   * Create a new ObjectFactory that can be used to create new instances of
   * schema derived classes for package:
   * com.mftvanak.edusys.ws.education.schemas.types
   * 
   */
  public ObjectFactory () {
  }

  /**
   * Create an instance of {@link CmsReservationType }
   * 
   */
  public CmsReservationType createCmsReservationType () {
    return new CmsReservationType ();
  }

  /**
   * Create an instance of {@link CmsGeneralReservationType }
   * 
   */
  public CmsGeneralReservationType createCmsGeneralReservationType () {
    return new CmsGeneralReservationType ();
  }

  /**
   * Create an instance of {@link GroupType }
   * 
   */
  public GroupType createGroupType () {
    return new GroupType ();
  }

  /**
   * Create an instance of {@link DepartmentType }
   * 
   */
  public DepartmentType createDepartmentType () {
    return new DepartmentType ();
  }

  /**
   * Create an instance of {@link InstituteType }
   * 
   */
  public InstituteType createInstituteType () {
    return new InstituteType ();
  }

}
