//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Com.Mftvanak.Edusys.Ui.Desktop.PhoneBook.AuthenticationServiceWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthenticationSoap11", Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
    public partial class AuthenticationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UserExistsByEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticationOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserExistsByUsernameOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeactivateTokenOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AuthenticationService() {
            this.Url = global::Com.Mftvanak.Edusys.Ui.Desktop.PhoneBook.Properties.Settings.Default.Com_Mftvanak_Edusys_Ui_Desktop_PhoneBook_AuthenticationServiceWebReference_AuthService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UserExistsByEmailCompletedEventHandler UserExistsByEmailCompleted;
        
        /// <remarks/>
        public event AuthenticationCompletedEventHandler AuthenticationCompleted;
        
        /// <remarks/>
        public event ValidateTokenCompletedEventHandler ValidateTokenCompleted;
        
        /// <remarks/>
        public event UserExistsByUsernameCompletedEventHandler UserExistsByUsernameCompleted;
        
        /// <remarks/>
        public event DeactivateTokenCompletedEventHandler DeactivateTokenCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UserExistsByEmailResponse", Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
        public UserExistsByEmailResponse UserExistsByEmail([System.Xml.Serialization.XmlElementAttribute(Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")] UserExistsByEmailRequest UserExistsByEmailRequest) {
            object[] results = this.Invoke("UserExistsByEmail", new object[] {
                        UserExistsByEmailRequest});
            return ((UserExistsByEmailResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UserExistsByEmailAsync(UserExistsByEmailRequest UserExistsByEmailRequest) {
            this.UserExistsByEmailAsync(UserExistsByEmailRequest, null);
        }
        
        /// <remarks/>
        public void UserExistsByEmailAsync(UserExistsByEmailRequest UserExistsByEmailRequest, object userState) {
            if ((this.UserExistsByEmailOperationCompleted == null)) {
                this.UserExistsByEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserExistsByEmailOperationCompleted);
            }
            this.InvokeAsync("UserExistsByEmail", new object[] {
                        UserExistsByEmailRequest}, this.UserExistsByEmailOperationCompleted, userState);
        }
        
        private void OnUserExistsByEmailOperationCompleted(object arg) {
            if ((this.UserExistsByEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserExistsByEmailCompleted(this, new UserExistsByEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AuthenticationResponse", Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
        public AuthenticationResponse Authentication([System.Xml.Serialization.XmlElementAttribute(Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")] AuthenticationRequest AuthenticationRequest) {
            object[] results = this.Invoke("Authentication", new object[] {
                        AuthenticationRequest});
            return ((AuthenticationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticationAsync(AuthenticationRequest AuthenticationRequest) {
            this.AuthenticationAsync(AuthenticationRequest, null);
        }
        
        /// <remarks/>
        public void AuthenticationAsync(AuthenticationRequest AuthenticationRequest, object userState) {
            if ((this.AuthenticationOperationCompleted == null)) {
                this.AuthenticationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticationOperationCompleted);
            }
            this.InvokeAsync("Authentication", new object[] {
                        AuthenticationRequest}, this.AuthenticationOperationCompleted, userState);
        }
        
        private void OnAuthenticationOperationCompleted(object arg) {
            if ((this.AuthenticationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticationCompleted(this, new AuthenticationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ValidateTokenResponse", Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
        public ValidateTokenResponse ValidateToken([System.Xml.Serialization.XmlElementAttribute(Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")] ValidateTokenRequest ValidateTokenRequest) {
            object[] results = this.Invoke("ValidateToken", new object[] {
                        ValidateTokenRequest});
            return ((ValidateTokenResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateTokenAsync(ValidateTokenRequest ValidateTokenRequest) {
            this.ValidateTokenAsync(ValidateTokenRequest, null);
        }
        
        /// <remarks/>
        public void ValidateTokenAsync(ValidateTokenRequest ValidateTokenRequest, object userState) {
            if ((this.ValidateTokenOperationCompleted == null)) {
                this.ValidateTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateTokenOperationCompleted);
            }
            this.InvokeAsync("ValidateToken", new object[] {
                        ValidateTokenRequest}, this.ValidateTokenOperationCompleted, userState);
        }
        
        private void OnValidateTokenOperationCompleted(object arg) {
            if ((this.ValidateTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateTokenCompleted(this, new ValidateTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UserExistsByUsernameResponse", Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
        public UserExistsByUsernameResponse UserExistsByUsername([System.Xml.Serialization.XmlElementAttribute(Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")] UserExistsByUsernameRequest UserExistsByUsernameRequest) {
            object[] results = this.Invoke("UserExistsByUsername", new object[] {
                        UserExistsByUsernameRequest});
            return ((UserExistsByUsernameResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UserExistsByUsernameAsync(UserExistsByUsernameRequest UserExistsByUsernameRequest) {
            this.UserExistsByUsernameAsync(UserExistsByUsernameRequest, null);
        }
        
        /// <remarks/>
        public void UserExistsByUsernameAsync(UserExistsByUsernameRequest UserExistsByUsernameRequest, object userState) {
            if ((this.UserExistsByUsernameOperationCompleted == null)) {
                this.UserExistsByUsernameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserExistsByUsernameOperationCompleted);
            }
            this.InvokeAsync("UserExistsByUsername", new object[] {
                        UserExistsByUsernameRequest}, this.UserExistsByUsernameOperationCompleted, userState);
        }
        
        private void OnUserExistsByUsernameOperationCompleted(object arg) {
            if ((this.UserExistsByUsernameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserExistsByUsernameCompleted(this, new UserExistsByUsernameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeactivateTokenResponse", Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
        public DeactivateTokenResponse DeactivateToken([System.Xml.Serialization.XmlElementAttribute(Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")] DeactivateTokenRequest DeactivateTokenRequest) {
            object[] results = this.Invoke("DeactivateToken", new object[] {
                        DeactivateTokenRequest});
            return ((DeactivateTokenResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeactivateTokenAsync(DeactivateTokenRequest DeactivateTokenRequest) {
            this.DeactivateTokenAsync(DeactivateTokenRequest, null);
        }
        
        /// <remarks/>
        public void DeactivateTokenAsync(DeactivateTokenRequest DeactivateTokenRequest, object userState) {
            if ((this.DeactivateTokenOperationCompleted == null)) {
                this.DeactivateTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeactivateTokenOperationCompleted);
            }
            this.InvokeAsync("DeactivateToken", new object[] {
                        DeactivateTokenRequest}, this.DeactivateTokenOperationCompleted, userState);
        }
        
        private void OnDeactivateTokenOperationCompleted(object arg) {
            if ((this.DeactivateTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeactivateTokenCompleted(this, new DeactivateTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
    public partial class UserExistsByEmailRequest {
        
        private string emailField;
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
    public partial class RoleType {
        
        private long idField;
        
        private string nodeIdField;
        
        private string nameField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string NodeId {
            get {
                return this.nodeIdField;
            }
            set {
                this.nodeIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
    public partial class UserExistsByEmailResponse {
        
        private int resultField;
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
    public partial class AuthenticationRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
    public partial class AuthenticationResponse {
        
        private string userIdField;
        
        private string tokenField;
        
        private RoleType[] rolesField;
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Roles")]
        public RoleType[] Roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
    public partial class ValidateTokenRequest {
        
        private string tokenField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
    public partial class ValidateTokenResponse {
        
        private string userIdField;
        
        private string usernameField;
        
        private RoleType[] rolesField;
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Roles")]
        public RoleType[] Roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
    public partial class UserExistsByUsernameRequest {
        
        private string usernameField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
    public partial class UserExistsByUsernameResponse {
        
        private int resultField;
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
    public partial class DeactivateTokenRequest {
        
        private string tokenField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://authentication.ws.edusys.mftvanak.com/schemas")]
    public partial class DeactivateTokenResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UserExistsByEmailCompletedEventHandler(object sender, UserExistsByEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserExistsByEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserExistsByEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserExistsByEmailResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserExistsByEmailResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AuthenticationCompletedEventHandler(object sender, AuthenticationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthenticationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthenticationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ValidateTokenCompletedEventHandler(object sender, ValidateTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ValidateTokenResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ValidateTokenResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UserExistsByUsernameCompletedEventHandler(object sender, UserExistsByUsernameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserExistsByUsernameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserExistsByUsernameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserExistsByUsernameResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserExistsByUsernameResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeactivateTokenCompletedEventHandler(object sender, DeactivateTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeactivateTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeactivateTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeactivateTokenResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeactivateTokenResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591